"""Specification for navigation: one curriculum, and everything generated from it stays current."""

import importlib
import pkgutil
import re
from pathlib import Path

import pytest

import primer
from primer.curriculum import CURRICULUM, neighbours, readme_section

ROOT = Path(__file__).resolve().parent.parent
NOT_LESSONS = {"primer.curriculum", "primer.glossary"}  # navigation aids, not lessons
SUPPORT_PACKAGES = ("primer.common.",)  # shared toy data and the stand-in embedder the lessons use


def lesson_modules_on_disk() -> set[str]:
    return {
        m.name
        for m in pkgutil.walk_packages(primer.__path__, "primer.")
        if not m.ispkg and not m.name.rsplit(".", 1)[-1].startswith("_") and m.name not in NOT_LESSONS
        and not m.name.startswith(SUPPORT_PACKAGES)
    }


class TestTheCurriculum:
    def test_given_every_lesson_on_disk_each_has_a_place_in_the_curriculum(self):
        # A lesson missing from the curriculum is invisible: no README row, no next/previous links.
        assert lesson_modules_on_disk() - {l.module for l in CURRICULUM} == set()

    def test_given_every_curriculum_entry_its_lesson_exists(self):
        missing = []
        for lesson in CURRICULUM:
            try:
                importlib.import_module(lesson.module)
            except ModuleNotFoundError:
                missing.append(lesson.module)
        assert missing == []

    def test_given_the_curriculum_no_lesson_appears_twice(self):
        modules = [l.module for l in CURRICULUM]
        assert len(modules) == len(set(modules))


class TestNextAndPrevious:
    def test_given_the_first_lesson_there_is_nothing_before_it(self):
        before, after = neighbours(CURRICULUM[0].module)
        assert before is None and after == CURRICULUM[1]

    def test_given_the_last_lesson_there_is_nothing_after_it(self):
        before, after = neighbours(CURRICULUM[-1].module)
        assert after is None and before == CURRICULUM[-2]


class TestTheReadme:
    def test_given_the_readme_every_lesson_it_names_exists(self):
        # The routes in "Start here" name lessons by module; a rename must not leave them pointing nowhere.
        named = set(re.findall(r"`(primer(?:\.[a-z_0-9]+)+)`", (ROOT / "README.md").read_text()))
        missing = []
        for module in named:
            try:
                importlib.import_module(module)
            except ModuleNotFoundError:
                try:  # a class or function inside a module, e.g. primer.agents.llm.ClaudeLLM
                    parent, _, attr = module.rpartition(".")
                    assert hasattr(importlib.import_module(parent), attr)
                except (ModuleNotFoundError, AssertionError):
                    missing.append(module)
        assert missing == []

    def test_given_the_curriculum_the_readme_reading_order_matches_it_exactly(self):
        # Hand-edited navigation goes stale; this section is generated by `make readme`.
        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN curriculum -->\n(.*?)<!-- END curriculum -->", readme, re.S)
        assert current, "README.md needs <!-- BEGIN curriculum --> / <!-- END curriculum --> markers"
        assert current.group(1) == readme_section(), "README is stale: run `make readme`"


REQUIRED_SECTIONS = ["## In 20 seconds", "## Self-test questions", "## Further reading"]


@pytest.mark.parametrize("lesson", CURRICULUM, ids=lambda l: l.module)
class TestEveryLessonMeetsTheStandard:
    def test_given_the_lesson_its_docstring_has_every_required_section(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        assert [s for s in REQUIRED_SECTIONS if s not in doc] == []

    def test_given_the_lesson_it_can_be_run_as_a_narrated_walkthrough(self, lesson):
        assert callable(getattr(importlib.import_module(lesson.module), "demo", None))

    def test_given_the_lesson_every_companion_it_links_to_is_in_the_paper_catalog(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        catalog = (ROOT / "docs" / "papers" / "CATALOG.md").read_text()
        slugs = set(re.findall(r"papers/([a-z0-9-]+)\.html", doc))
        assert {s for s in slugs if f"`{s}`" not in catalog} == set()


class TestTheSite:
    def test_given_the_curriculum_the_home_page_links_every_lesson(self):
        from tools.docsite import render_home

        home = render_home()
        missing = [l.module for l in CURRICULUM if f'href="{l.module.replace(".", "/")}.html"' not in home]
        assert missing == []

    def test_given_a_middle_lesson_its_nav_links_the_previous_and_next_lessons(self):
        from tools.docsite import lesson_nav

        nav = lesson_nav("primer.ml.attention")
        # Pages live at primer/ml/attention.html, so neighbours in the same folder are siblings.
        assert 'href="deep_nets.html"' in nav and 'href="positional.html"' in nav

    def test_given_a_lesson_its_nav_names_the_part_it_belongs_to(self):
        from tools.docsite import lesson_nav

        assert "Embeddings, the centerpiece" in lesson_nav("primer.ml.embeddings.ann")

    def test_given_the_catalog_every_paper_is_listed_with_its_slug(self):
        from tools.docsite import catalog

        slugs = [p["slug"] for p in catalog()]
        assert "attention-is-all-you-need" in slugs and "hnsw" in slugs
        assert len(slugs) == len(set(slugs))


class TestTheSelfTestBook:
    def test_given_the_lessons_the_self_test_book_matches_their_questions_exactly(self):
        from primer.curriculum import self_test_book

        # One source of truth: questions live in the lesson docstrings; the book is generated.
        assert (ROOT / "docs" / "SELF_TEST.md").read_text() == self_test_book(), "stale: run `make readme`"

    def test_given_the_self_test_book_it_follows_reading_order(self):
        from primer.curriculum import self_test_book

        book = self_test_book()
        assert book.index("Math notation, from zero") < book.index("Attention") < book.index("Guardrails")


class TestBigQuestions:
    def test_given_every_big_question_each_lesson_on_its_route_exists(self):
        from primer.curriculum import BIG_QUESTIONS

        known = {l.module for l in CURRICULUM}
        assert [m for q in BIG_QUESTIONS for m in q.route if m not in known] == []

    def test_given_the_curriculum_every_lesson_belongs_to_at_least_one_big_question(self):
        # A lesson no big question needs is either missing from the map or not pulling its weight.
        from primer.curriculum import BIG_QUESTIONS

        covered = {m for q in BIG_QUESTIONS for m in q.route}
        assert [l.module for l in CURRICULUM if l.module not in covered] == []

    def test_given_every_big_question_its_answer_has_a_spine_of_three_to_seven_points(self):
        from primer.curriculum import BIG_QUESTIONS

        assert [q.question for q in BIG_QUESTIONS if not 3 <= len(q.spine) <= 7] == []

    def test_given_the_big_questions_the_generated_page_is_current(self):
        from primer.curriculum import big_questions_page

        assert (ROOT / "docs" / "BIG_QUESTIONS.md").read_text() == big_questions_page(), "stale: run `make readme`"

    def test_given_the_big_questions_the_readme_map_is_current(self):
        from primer.curriculum import big_questions_table

        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN big-questions -->\n(.*?)<!-- END big-questions -->", readme, re.S)
        assert current and current.group(1) == big_questions_table(), "stale: run `make readme`"
