"""Specification for navigation: one curriculum, and everything generated from it stays current."""

import importlib
import pkgutil
import re
from pathlib import Path

import pytest

import primer
from primer.curriculum import CURRICULUM, neighbours, readme_section

ROOT = Path(__file__).resolve().parent.parent
NOT_LESSONS = {"primer.curriculum", "primer.glossary"}  # navigation aids, not lessons
SUPPORT_PACKAGES = ("primer.common.",)  # shared toy data and the stand-in embedder the lessons use


def lesson_modules_on_disk() -> set[str]:
    return {
        m.name
        for m in pkgutil.walk_packages(primer.__path__, "primer.")
        if not m.ispkg and not m.name.rsplit(".", 1)[-1].startswith("_") and m.name not in NOT_LESSONS
        and not m.name.startswith(SUPPORT_PACKAGES)
    }


class TestTheCurriculum:
    def test_given_every_lesson_on_disk_each_has_a_place_in_the_curriculum(self):
        # A lesson missing from the curriculum is invisible: no README row, no next/previous links.
        assert lesson_modules_on_disk() - {l.module for l in CURRICULUM} == set()

    def test_given_every_curriculum_entry_its_lesson_exists(self):
        missing = []
        for lesson in CURRICULUM:
            try:
                importlib.import_module(lesson.module)
            except ModuleNotFoundError:
                missing.append(lesson.module)
        assert missing == []

    def test_given_the_curriculum_no_lesson_appears_twice(self):
        modules = [l.module for l in CURRICULUM]
        assert len(modules) == len(set(modules))


class TestNextAndPrevious:
    def test_given_the_first_lesson_there_is_nothing_before_it(self):
        before, after = neighbours(CURRICULUM[0].module)
        assert before is None and after == CURRICULUM[1]

    def test_given_the_last_lesson_there_is_nothing_after_it(self):
        before, after = neighbours(CURRICULUM[-1].module)
        assert after is None and before == CURRICULUM[-2]


class TestTheReadme:
    def test_given_the_readme_every_lesson_it_names_exists(self):
        # The routes in "Start here" name lessons by module; a rename must not leave them pointing nowhere.
        named = set(re.findall(r"`(primer(?:\.[a-z_0-9]+)+)`", (ROOT / "README.md").read_text()))
        missing = []
        for module in named:
            try:
                importlib.import_module(module)
            except ModuleNotFoundError:
                try:  # a class or function inside a module, e.g. primer.agents.llm.ClaudeLLM
                    parent, _, attr = module.rpartition(".")
                    assert hasattr(importlib.import_module(parent), attr)
                except (ModuleNotFoundError, AssertionError):
                    missing.append(module)
        assert missing == []

    def test_given_the_curriculum_the_readme_reading_order_matches_it_exactly(self):
        # Hand-edited navigation goes stale; this section is generated by `make readme`.
        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN curriculum -->\n(.*?)<!-- END curriculum -->", readme, re.S)
        assert current, "README.md needs <!-- BEGIN curriculum --> / <!-- END curriculum --> markers"
        assert current.group(1) == readme_section(), "README is stale: run `make readme`"


REQUIRED_SECTIONS = ["## In 20 seconds", "## Self-test questions", "## Further reading"]


@pytest.mark.parametrize("lesson", CURRICULUM, ids=lambda l: l.module)
class TestEveryLessonMeetsTheStandard:
    def test_given_the_lesson_its_docstring_has_every_required_section(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        assert [s for s in REQUIRED_SECTIONS if s not in doc] == []

    def test_given_the_lesson_it_can_be_run_as_a_narrated_walkthrough(self, lesson):
        assert callable(getattr(importlib.import_module(lesson.module), "demo", None))

    def test_given_the_lesson_every_companion_it_links_to_is_in_the_paper_catalog(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        catalog = (ROOT / "docs" / "papers" / "CATALOG.md").read_text()
        slugs = set(re.findall(r"papers/([a-z0-9-]+)\.html", doc))
        assert {s for s in slugs if f"`{s}`" not in catalog} == set()


class TestTheSite:
    def test_given_the_curriculum_the_home_page_links_every_lesson(self):
        from tools.docsite import render_home

        home = render_home()
        missing = [l.module for l in CURRICULUM if f'href="{l.module.replace(".", "/")}.html"' not in home]
        assert missing == []

    def test_given_a_middle_lesson_its_nav_links_the_previous_and_next_lessons(self):
        from tools.docsite import lesson_nav

        nav = lesson_nav("primer.ml.attention")
        # Pages live at primer/ml/attention.html, so neighbours in the same folder are siblings.
        assert 'href="deep_nets.html"' in nav and 'href="positional.html"' in nav

    def test_given_a_lesson_its_nav_names_the_part_it_belongs_to(self):
        from tools.docsite import lesson_nav

        assert "Embeddings, the centerpiece" in lesson_nav("primer.ml.embeddings.ann")

    def test_given_the_catalog_every_paper_is_listed_with_its_slug(self):
        from tools.docsite import catalog

        slugs = [p["slug"] for p in catalog()]
        assert "attention-is-all-you-need" in slugs and "hnsw" in slugs
        assert len(slugs) == len(set(slugs))


class TestTheSelfTestBook:
    def test_given_the_lessons_the_self_test_book_matches_their_questions_exactly(self):
        from primer.curriculum import self_test_book

        # One source of truth: questions live in the lesson docstrings; the book is generated.
        assert (ROOT / "docs" / "SELF_TEST.md").read_text() == self_test_book(), "stale: run `make readme`"

    def test_given_the_self_test_book_it_follows_reading_order(self):
        from primer.curriculum import self_test_book

        book = self_test_book()
        assert book.index("Math notation, from zero") < book.index("Attention") < book.index("Guardrails")


class TestBigQuestions:
    def test_given_every_big_question_each_lesson_on_its_route_exists(self):
        from primer.curriculum import BIG_QUESTIONS

        known = {l.module for l in CURRICULUM}
        assert [m for q in BIG_QUESTIONS for m in q.route if m not in known] == []

    def test_given_the_curriculum_every_lesson_belongs_to_at_least_one_big_question(self):
        # A lesson no big question needs is either missing from the map or not pulling its weight.
        from primer.curriculum import BIG_QUESTIONS

        covered = {m for q in BIG_QUESTIONS for m in q.route}
        assert [l.module for l in CURRICULUM if l.module not in covered] == []

    def test_given_every_big_question_its_answer_has_a_spine_of_three_to_seven_points(self):
        from primer.curriculum import BIG_QUESTIONS

        assert [q.question for q in BIG_QUESTIONS if not 3 <= len(q.spine) <= 7] == []

    def test_given_the_big_questions_the_generated_page_is_current(self):
        from primer.curriculum import big_questions_page

        assert (ROOT / "docs" / "BIG_QUESTIONS.md").read_text() == big_questions_page(), "stale: run `make readme`"

    def test_given_the_big_questions_the_readme_map_is_current(self):
        from primer.curriculum import big_questions_table

        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN big-questions -->\n(.*?)<!-- END big-questions -->", readme, re.S)
        assert current and current.group(1) == big_questions_table(), "stale: run `make readme`"


def _resolve(module, name: str):
    """The object a backticked name in `module`'s docstring points at, or None."""
    if name.startswith("primer."):
        parts = name.split(".")
        for i in range(len(parts), 0, -1):
            try:
                obj = importlib.import_module(".".join(parts[:i]))
            except ImportError:
                continue
            for p in parts[i:]:
                obj = getattr(obj, p, None)
            return obj
        return None
    obj = module
    for p in name.split("."):
        obj = getattr(obj, p, None)
    return obj


SHA = "0123456789abcdef0123456789abcdef01234567"


@pytest.fixture
def published(monkeypatch):
    """A build running on GitHub Actions, as the Pages workflow does."""
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    monkeypatch.setenv("GITHUB_SHA", SHA)
    monkeypatch.setenv("GITHUB_SERVER_URL", "https://github.com")
    monkeypatch.setenv("GITHUB_REPOSITORY", "someone/a-fork")


@pytest.fixture
def local(monkeypatch):
    """A build on the reader's own machine, from their own checkout."""
    for name in ("GITHUB_ACTIONS", "GITHUB_SHA", "GITHUB_REPOSITORY"):
        monkeypatch.delenv(name, raising=False)


def _first_line_of(path: str, prefix: str) -> int:
    # Found by reading the file, independently of how the site builder locates code.
    return next(i for i, line in enumerate((ROOT / path).read_text().splitlines(), 1) if line.startswith(prefix))


class TestWhereCodeLinksPoint:
    # The published site holds only HTML, so its code links go to GitHub, pinned to the commit it was
    # built from. A site built locally links to the reader's own files, so it always shows their code.

    def test_given_a_local_build_a_lesson_links_its_source_file_in_your_own_checkout(self, local):
        from tools.docsite import lesson_nav

        # primer/ml/attention.html sits in docs/html/primer/ml/; four levels up is the repository root.
        assert 'href="../../../../primer/ml/attention.py"' in lesson_nav("primer.ml.attention")

    def test_given_a_local_build_a_lesson_links_the_tests_in_your_own_checkout(self, local):
        from tools.docsite import lesson_nav

        assert 'href="../../../../../tests/test_emb_ann.py"' in lesson_nav("primer.ml.embeddings.ann")

    def test_given_a_published_build_a_lesson_links_its_source_at_the_commit_the_site_was_built_from(self, published):
        from tools.docsite import lesson_nav

        assert f'href="https://github.com/someone/a-fork/blob/{SHA}/primer/ml/attention.py"' in lesson_nav("primer.ml.attention")

    def test_given_a_published_build_a_function_links_its_exact_lines_at_that_commit(self, published):
        from tools.docsite import link_members_to_source

        page = '<section id="run_chain"><label class="view-source-button" for="run_chain-view-source"><span>View Source</span></label></section>'
        linked = link_members_to_source(page, "primer.agents.orchestration", "primer/agents/orchestration.html")
        first = _first_line_of("primer/agents/orchestration.py", "def run_chain(")
        assert f'href="https://github.com/someone/a-fork/blob/{SHA}/primer/agents/orchestration.py#L{first}-L' in linked

    def test_given_a_local_build_a_function_links_the_file_in_your_own_checkout(self, local):
        from tools.docsite import link_members_to_source

        page = '<section id="run_chain"><label class="view-source-button" for="run_chain-view-source"><span>View Source</span></label></section>'
        linked = link_members_to_source(page, "primer.agents.orchestration", "primer/agents/orchestration.html")
        assert 'href="../../../../primer/agents/orchestration.py"' in linked

    def test_given_a_member_inherited_from_outside_the_repository_it_gets_no_source_link(self, published):
        from tools.docsite import link_members_to_source

        # LLM is a typing.Protocol; its __init__ lives in the standard library, not in this repository.
        page = '<div id="LLM.__init__"><label class="view-source-button" for="LLM.__init__-view-source"><span>View Source</span></label></div>'
        assert "code-source" not in link_members_to_source(page, "primer.agents.llm", "primer/agents/llm.html")

    def test_given_a_published_build_the_home_page_links_the_repository_it_was_built_from(self, published):
        from tools.docsite import render_home

        home = render_home()
        assert 'href="https://github.com/someone/a-fork"' in home and f'href="https://github.com/someone/a-fork/blob/{SHA}/LICENSE"' in home

    @pytest.mark.parametrize("remote", [
        "https://github.com/someone/a-fork.git",
        "https://github.com/someone/a-fork",
        "git@github.com:someone/a-fork.git",
        "ssh://git@github.com/someone/a-fork.git",
    ])
    def test_given_any_form_of_git_remote_the_repository_address_is_its_web_page(self, remote):
        from tools.docsite import web_url_of_remote

        assert web_url_of_remote(remote) == "https://github.com/someone/a-fork"


class TestLinksIntoTheCode:
    def test_given_every_lesson_exactly_one_test_file_specifies_it(self):
        from primer.curriculum import tests_for

        assert [l.module for l in CURRICULUM if not (ROOT / tests_for(l.module)).exists()] == []

    @pytest.mark.parametrize("lesson", [l.module for l in CURRICULUM])
    def test_given_the_lesson_every_name_its_in_code_lines_cite_is_public_code_that_exists(self, lesson):
        module = importlib.import_module(lesson)
        # A paragraph runs until the blank line, so names on wrapped lines count too.
        paragraphs = re.findall(r"\*\*In code:\*\*(.*?)(?:\n\s*\n|\Z)", module.__doc__, re.S)
        cited = [n for p in paragraphs for n in re.findall(r"`([A-Za-z_][\w.]*)(?:\(\))?`", p)]
        # pdoc links a short name only when this module defines it; anything else must be written dotted.
        # It never links private names, so those would be dead ends too.
        source = Path(module.__file__).read_text()

        def defined_here(name: str) -> bool:
            top = name.split(".")[0]
            owner = getattr(getattr(module, top, None), "__module__", None)
            # Plain data (a dict, a list) has no __module__; it is ours if the module assigns it at top level.
            return owner == lesson if owner else re.search(rf"^{re.escape(top)}\s*[:=]", source, re.M) is not None

        broken = [n for n in cited if n.split(".")[-1].startswith("_") or _resolve(module, n) is None
                  or not (n.startswith("primer.") or defined_here(n))]
        assert broken == []

    def test_given_the_readme_each_lesson_row_links_its_page_on_the_live_site(self):
        from primer.curriculum import SITE_URL

        assert f"({SITE_URL}primer/ml/attention.html)" in readme_section()

    def test_given_the_readme_it_says_how_to_clone_the_real_repository(self):
        from primer.curriculum import REPO_URL

        assert f"git clone {REPO_URL}" in (ROOT / "README.md").read_text()


class TestCheckingLinksIntoThisRepository:
    # Links to our own GitHub files are checked against the working tree, so they are verified offline.
    def test_given_a_link_to_lines_that_exist_it_passes(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/primer/ml/attention.py#L1-L3") is None

    def test_given_a_link_pinned_to_a_commit_past_the_end_of_a_file_it_is_reported(self, published):
        from tools.sitecheck import own_repo_problem

        # On GitHub Actions the checkout is that commit, so the working tree is what the link will show.
        url = f"https://github.com/someone/a-fork/blob/{SHA}/LICENSE#L5-L999"
        assert own_repo_problem(url) == "LICENSE has 94 lines, link asks for L5-L999"

    def test_given_a_link_to_a_file_that_does_not_exist_it_is_reported(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/primer/ml/nope.py") == "no such file: primer/ml/nope.py"

    def test_given_a_link_past_the_end_of_a_file_it_is_reported(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/LICENSE#L5-L999") == "LICENSE has 94 lines, link asks for L5-L999"

    def test_given_an_in_code_line_whose_names_did_not_become_links_it_is_reported(self):
        from tools.sitecheck import unlinked_code_names

        # pdoc puts the link inside the code element.
        page = '<p><strong>In code:</strong> <code><a href="#run">run</a></code> and <code>_helper</code> do it.</p>'
        assert unlinked_code_names(page) == ["_helper"]


class TestPagesThatAreNotLessons:
    def test_given_a_page_that_is_not_a_lesson_its_bar_leads_home_and_to_github(self):
        from primer.curriculum import REPO_URL
        from tools.docsite import site_nav

        nav = site_nav("primer/glossary.html")
        assert 'href="../index.html"' in nav and f'href="{REPO_URL}"' in nav


def _hex_rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))


class TestOneThemeEverywhere:
    THEME_CSS = ROOT / "docs" / "assets" / "theme.css"

    def test_given_dark_mode_the_page_background_is_a_neutral_grey_not_a_navy(self):
        dark = re.search(r':root\[data-theme="dark"\]\s*\{(.*?)\}', self.THEME_CSS.read_text(), re.S).group(1)
        r, g, b = _hex_rgb(re.search(r"--p-bg:\s*(#[0-9a-fA-F]{6})", dark).group(1))
        # Navy is blue well above red and green; a neutral grey keeps the three channels within a few steps.
        assert max(r, g, b) - min(r, g, b) <= 6

    def test_given_the_system_prefers_dark_and_no_choice_was_made_the_same_dark_palette_applies(self):
        css = self.THEME_CSS.read_text()
        forced = re.search(r':root\[data-theme="dark"\]\s*\{(.*?)\}', css, re.S).group(1)
        auto = re.search(r':root:not\(\[data-theme="light"\]\)\s*\{(.*?)\}', css, re.S).group(1)
        assert forced.split() == auto.split()

    def test_given_a_lesson_its_nav_has_the_theme_switcher(self):
        from tools.docsite import lesson_nav

        assert "data-theme-toggle" in lesson_nav("primer.ml.attention")

    def test_given_a_page_that_is_not_a_lesson_its_bar_has_the_theme_switcher(self):
        from tools.docsite import site_nav

        assert "data-theme-toggle" in site_nav("primer/glossary.html")

    def test_given_the_home_page_it_uses_the_shared_theme_and_has_the_switcher(self):
        from tools.docsite import render_home

        home = render_home()
        assert 'href="assets/theme.css"' in home and 'src="assets/theme.js"' in home and "data-theme-toggle" in home

    def test_given_a_pdoc_page_the_theme_loads_in_its_head_so_it_never_flashes_the_wrong_colours(self):
        from tools.docsite import add_theme

        page = add_theme("<html><head><title>x</title></head><body></body></html>", "primer/ml/attention.html")
        head = page.split("</head>")[0]
        assert 'href="../../assets/theme.css"' in head and 'src="../../assets/theme.js"' in head

    @pytest.mark.parametrize("companion", sorted(p.name for p in (ROOT / "docs" / "papers").glob("*.html")))
    def test_given_a_paper_companion_it_uses_the_shared_theme(self, companion):
        head = (ROOT / "docs" / "papers" / companion).read_text().split("</head>")[0]
        assert 'href="../assets/theme.css"' in head and 'src="../assets/theme.js"' in head


class TestNoPageRepeatsTheHomePage:
    # pdoc makes a page for each package, but a package's page would only repeat the reading list the
    # home page already shows, so each one forwards to that section of the home page instead.

    def test_given_the_package_pages_each_forwards_to_the_home_page_section_listing_its_lessons(self):
        from tools.docsite import package_forwards

        assert package_forwards() == {
            "primer.html": "index.html#lessons",
            "primer/ml.html": "../index.html#ml",
            "primer/ml/embeddings.html": "../../index.html#embeddings",
            "primer/agents.html": "../index.html#agents",
        }

    def test_given_a_forwarded_page_it_still_offers_a_plain_link_for_browsers_that_do_not_redirect(self):
        from tools.docsite import forward_page

        page = forward_page("../index.html#ml")
        assert 'http-equiv="refresh" content="0; url=../index.html#ml"' in page and 'href="../index.html#ml"' in page

    def test_given_the_home_page_every_section_a_package_forwards_to_exists(self):
        from tools.docsite import package_forwards, render_home

        home = render_home()
        anchors = {target.split("#")[1] for target in package_forwards().values()}
        assert [a for a in anchors if f'id="{a}"' not in home] == []

    def test_given_the_home_page_it_no_longer_sends_readers_to_the_package_overview(self):
        from tools.docsite import render_home

        assert 'href="primer.html"' not in render_home()

    def test_given_pdocs_links_to_a_package_page_they_go_straight_to_the_home_page_instead(self):
        from tools.docsite import skip_forwarded_pages

        # pdoc's title and sidebar link each lesson to its package pages.
        page = '<a href="./../../../primer.html">primer</a>.<a href="./../../ml.html">ml</a> <a href="../embeddings.html">up</a>'
        linked = skip_forwarded_pages(page, "primer/ml/embeddings/ann.html")
        assert linked == ('<a href="../../../index.html#lessons">primer</a>.<a href="../../../index.html#ml">ml</a> '
                          '<a href="../../../index.html#embeddings">up</a>')

    def test_given_a_link_to_a_lesson_it_is_left_alone(self):
        from tools.docsite import skip_forwarded_pages

        page = '<a href="../attention.html#softmax">softmax</a>'
        assert skip_forwarded_pages(page, "primer/ml/transformer.html") == page
