"""Specification for navigation: one curriculum, and everything generated from it stays current."""

import importlib
import pkgutil
import re
from pathlib import Path

import pytest

import primer
from primer.curriculum import CURRICULUM, neighbours, readme_section

ROOT = Path(__file__).resolve().parent.parent
NOT_LESSONS = {"primer.curriculum", "primer.glossary"}  # navigation aids, not lessons
SUPPORT_PACKAGES = ("primer.common.",)  # shared toy data and the stand-in embedder the lessons use


def lesson_modules_on_disk() -> set[str]:
    return {
        m.name
        for m in pkgutil.walk_packages(primer.__path__, "primer.")
        if not m.ispkg and not m.name.rsplit(".", 1)[-1].startswith("_") and m.name not in NOT_LESSONS
        and not m.name.startswith(SUPPORT_PACKAGES)
    }


class TestTheCurriculum:
    def test_given_every_lesson_on_disk_each_has_a_place_in_the_curriculum(self):
        # A lesson missing from the curriculum is invisible: no README row, no next/previous links.
        assert lesson_modules_on_disk() - {l.module for l in CURRICULUM} == set()

    def test_given_every_curriculum_entry_its_lesson_exists(self):
        missing = []
        for lesson in CURRICULUM:
            try:
                importlib.import_module(lesson.module)
            except ModuleNotFoundError:
                missing.append(lesson.module)
        assert missing == []

    def test_given_the_curriculum_no_lesson_appears_twice(self):
        modules = [l.module for l in CURRICULUM]
        assert len(modules) == len(set(modules))


class TestNextAndPrevious:
    def test_given_the_first_lesson_there_is_nothing_before_it(self):
        before, after = neighbours(CURRICULUM[0].module)
        assert before is None and after == CURRICULUM[1]

    def test_given_the_last_lesson_there_is_nothing_after_it(self):
        before, after = neighbours(CURRICULUM[-1].module)
        assert after is None and before == CURRICULUM[-2]


class TestTheReadme:
    def test_given_the_readme_every_lesson_it_names_exists(self):
        # The routes in "Start here" name lessons by module; a rename must not leave them pointing nowhere.
        named = set(re.findall(r"`(primer(?:\.[a-z_0-9]+)+)`", (ROOT / "README.md").read_text()))
        missing = []
        for module in named:
            try:
                importlib.import_module(module)
            except ModuleNotFoundError:
                try:  # a class or function inside a module, e.g. primer.agents.llm.ClaudeLLM
                    parent, _, attr = module.rpartition(".")
                    assert hasattr(importlib.import_module(parent), attr)
                except (ModuleNotFoundError, AssertionError):
                    missing.append(module)
        assert missing == []

    def test_given_the_curriculum_the_readme_reading_order_matches_it_exactly(self):
        # Hand-edited navigation goes stale; this section is generated by `make readme`.
        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN curriculum -->\n(.*?)<!-- END curriculum -->", readme, re.S)
        assert current, "README.md needs <!-- BEGIN curriculum --> / <!-- END curriculum --> markers"
        assert current.group(1) == readme_section(), "README is stale: run `make readme`"


REQUIRED_SECTIONS = ["## In 20 seconds", "## Self-test questions", "## Further reading"]


@pytest.mark.parametrize("lesson", CURRICULUM, ids=lambda l: l.module)
class TestEveryLessonMeetsTheStandard:
    def test_given_the_lesson_its_docstring_has_every_required_section(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        assert [s for s in REQUIRED_SECTIONS if s not in doc] == []

    def test_given_the_lesson_it_can_be_run_as_a_narrated_walkthrough(self, lesson):
        assert callable(getattr(importlib.import_module(lesson.module), "demo", None))

    def test_given_the_lesson_every_companion_it_links_to_is_in_the_paper_catalog(self, lesson):
        doc = importlib.import_module(lesson.module).__doc__ or ""
        catalog = (ROOT / "docs" / "papers" / "CATALOG.md").read_text()
        slugs = set(re.findall(r"papers/([a-z0-9-]+)\.html", doc))
        assert {s for s in slugs if f"`{s}`" not in catalog} == set()

    def test_given_the_lesson_every_companion_it_links_to_lists_it_among_the_lessons_that_build_it(self, lesson):
        from tools.docsite import catalog

        # The companion's "Lessons that build this" box comes from the catalog, so the link must run both ways.
        doc = importlib.import_module(lesson.module).__doc__ or ""
        slugs = set(re.findall(r"papers/([a-z0-9-]+)\.html", doc))
        lessons_of = {p["slug"]: p["lessons"] for p in catalog()}
        assert sorted(s for s in slugs if s in lessons_of and lesson.module not in lessons_of[s]) == []

    def test_given_the_lesson_cites_a_paper_that_has_a_companion_it_links_the_companion(self, lesson):
        from tools.docsite import catalog

        # A reader at the citation should reach the walkthrough; a companion written later must be linked back.
        doc = importlib.import_module(lesson.module).__doc__ or ""
        papers = doc.split("## The papers behind this lesson")[-1].split("## Further reading")[0]
        cited = [p["slug"] for p in catalog()
                 if p["exists"] and lesson.module in p["lessons"] and any(src in papers for src in p["sources"])]
        assert sorted(s for s in cited if f"papers/{s}.html" not in papers) == []


class TestTheSite:
    def test_given_the_curriculum_the_home_page_links_every_lesson(self):
        from tools.docsite import render_home

        home = render_home()
        missing = [l.module for l in CURRICULUM if f'href="{l.module.replace(".", "/")}.html"' not in home]
        assert missing == []

    def test_given_a_middle_lesson_its_nav_links_the_previous_and_next_lessons(self):
        from tools.docsite import lesson_nav

        nav = lesson_nav("primer.ml.attention")
        # Pages live at primer/ml/attention.html, so neighbours in the same folder are siblings.
        assert 'href="deep_nets.html"' in nav and 'href="positional.html"' in nav

    def test_given_a_lesson_its_nav_names_the_part_it_belongs_to(self):
        from tools.docsite import lesson_nav

        assert "Embeddings, the centerpiece" in lesson_nav("primer.ml.embeddings.ann")

    def test_given_the_catalog_every_paper_is_listed_with_its_slug(self):
        from tools.docsite import catalog

        slugs = [p["slug"] for p in catalog()]
        assert "attention-is-all-you-need" in slugs and "hnsw" in slugs
        assert len(slugs) == len(set(slugs))


class TestTheSelfTestBook:
    def test_given_the_lessons_the_self_test_book_matches_their_questions_exactly(self):
        from primer.curriculum import self_test_book

        # One source of truth: questions live in the lesson docstrings; the book is generated.
        assert (ROOT / "docs" / "SELF_TEST.md").read_text() == self_test_book(), "stale: run `make readme`"

    def test_given_the_self_test_book_it_follows_reading_order(self):
        from primer.curriculum import self_test_book

        book = self_test_book()
        assert book.index("Math notation, from zero") < book.index("Attention") < book.index("Guardrails")


class TestBigQuestions:
    def test_given_every_big_question_each_lesson_on_its_route_exists(self):
        from primer.curriculum import BIG_QUESTIONS

        known = {l.module for l in CURRICULUM}
        assert [m for q in BIG_QUESTIONS for m in q.route if m not in known] == []

    def test_given_the_curriculum_every_lesson_belongs_to_at_least_one_big_question(self):
        # A lesson no big question needs is either missing from the map or not pulling its weight.
        from primer.curriculum import BIG_QUESTIONS

        covered = {m for q in BIG_QUESTIONS for m in q.route}
        assert [l.module for l in CURRICULUM if l.module not in covered] == []

    def test_given_every_big_question_its_short_version_has_three_to_seven_ideas(self):
        from primer.curriculum import BIG_QUESTIONS

        assert [q.question for q in BIG_QUESTIONS if not 3 <= len(q.in_brief) <= 7] == []

    def test_given_the_big_questions_the_generated_page_is_current(self):
        from primer.curriculum import big_questions_page

        assert (ROOT / "docs" / "BIG_QUESTIONS.md").read_text() == big_questions_page(), "stale: run `make readme`"

    def test_given_the_big_questions_the_readme_map_is_current(self):
        from primer.curriculum import big_questions_table

        readme = (ROOT / "README.md").read_text()
        current = re.search(r"<!-- BEGIN big-questions -->\n(.*?)<!-- END big-questions -->", readme, re.S)
        assert current and current.group(1) == big_questions_table(), "stale: run `make readme`"


def _resolve(module, name: str):
    """The object a backticked name in `module`'s docstring points at, or None."""
    if name.startswith("primer."):
        parts = name.split(".")
        for i in range(len(parts), 0, -1):
            try:
                obj = importlib.import_module(".".join(parts[:i]))
            except ImportError:
                continue
            for p in parts[i:]:
                obj = getattr(obj, p, None)
            return obj
        return None
    obj = module
    for p in name.split("."):
        obj = getattr(obj, p, None)
    return obj


SHA = "0123456789abcdef0123456789abcdef01234567"


@pytest.fixture
def published(monkeypatch):
    """A build running on GitHub Actions, as the Pages workflow does."""
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    monkeypatch.setenv("GITHUB_SHA", SHA)
    monkeypatch.setenv("GITHUB_SERVER_URL", "https://github.com")
    monkeypatch.setenv("GITHUB_REPOSITORY", "someone/a-fork")


@pytest.fixture
def local(monkeypatch):
    """A build on the reader's own machine, from their own checkout."""
    for name in ("GITHUB_ACTIONS", "GITHUB_SHA", "GITHUB_REPOSITORY"):
        monkeypatch.delenv(name, raising=False)


def _first_line_of(path: str, prefix: str) -> int:
    # Found by reading the file, independently of how the site builder locates code.
    return next(i for i, line in enumerate((ROOT / path).read_text().splitlines(), 1) if line.startswith(prefix))


class TestWhereCodeLinksPoint:
    # The published site holds only HTML, so its code links go to GitHub, pinned to the commit it was
    # built from. A site built locally links to the reader's own files, so it always shows their code.

    def test_given_a_local_build_a_lesson_links_its_source_file_in_your_own_checkout(self, local):
        from tools.docsite import lesson_nav

        # primer/ml/attention.html sits in docs/html/primer/ml/; four levels up is the repository root.
        assert 'href="../../../../primer/ml/attention.py"' in lesson_nav("primer.ml.attention")

    def test_given_a_local_build_a_lesson_links_the_tests_in_your_own_checkout(self, local):
        from tools.docsite import lesson_nav

        assert 'href="../../../../../tests/test_emb_ann.py"' in lesson_nav("primer.ml.embeddings.ann")

    def test_given_a_published_build_a_lesson_links_its_source_at_the_commit_the_site_was_built_from(self, published):
        from tools.docsite import lesson_nav

        assert f'href="https://github.com/someone/a-fork/blob/{SHA}/primer/ml/attention.py"' in lesson_nav("primer.ml.attention")

    def test_given_a_published_build_a_function_links_its_exact_lines_at_that_commit(self, published):
        from tools.docsite import link_members_to_source

        page = '<section id="run_chain"><label class="view-source-button" for="run_chain-view-source"><span>View Source</span></label></section>'
        linked = link_members_to_source(page, "primer.agents.orchestration", "primer/agents/orchestration.html")
        first = _first_line_of("primer/agents/orchestration.py", "def run_chain(")
        assert f'href="https://github.com/someone/a-fork/blob/{SHA}/primer/agents/orchestration.py#L{first}-L' in linked

    def test_given_a_local_build_a_function_links_the_file_in_your_own_checkout(self, local):
        from tools.docsite import link_members_to_source

        page = '<section id="run_chain"><label class="view-source-button" for="run_chain-view-source"><span>View Source</span></label></section>'
        linked = link_members_to_source(page, "primer.agents.orchestration", "primer/agents/orchestration.html")
        assert 'href="../../../../primer/agents/orchestration.py"' in linked

    def test_given_a_member_inherited_from_outside_the_repository_it_gets_no_source_link(self, published):
        from tools.docsite import link_members_to_source

        # LLM is a typing.Protocol; its __init__ lives in the standard library, not in this repository.
        page = '<div id="LLM.__init__"><label class="view-source-button" for="LLM.__init__-view-source"><span>View Source</span></label></div>'
        assert "code-source" not in link_members_to_source(page, "primer.agents.llm", "primer/agents/llm.html")

    def test_given_a_published_build_the_home_page_links_the_repository_it_was_built_from(self, published):
        from tools.docsite import render_home

        home = render_home()
        assert 'href="https://github.com/someone/a-fork"' in home and f'href="https://github.com/someone/a-fork/blob/{SHA}/LICENSE"' in home

    @pytest.mark.parametrize("remote", [
        "https://github.com/someone/a-fork.git",
        "https://github.com/someone/a-fork",
        "git@github.com:someone/a-fork.git",
        "ssh://git@github.com/someone/a-fork.git",
    ])
    def test_given_any_form_of_git_remote_the_repository_address_is_its_web_page(self, remote):
        from tools.docsite import web_url_of_remote

        assert web_url_of_remote(remote) == "https://github.com/someone/a-fork"


class TestLinksIntoTheCode:
    def test_given_every_lesson_exactly_one_test_file_specifies_it(self):
        from primer.curriculum import tests_for

        assert [l.module for l in CURRICULUM if not (ROOT / tests_for(l.module)).exists()] == []

    @pytest.mark.parametrize("lesson", [l.module for l in CURRICULUM])
    def test_given_the_lesson_every_name_its_in_code_lines_cite_is_public_code_that_exists(self, lesson):
        module = importlib.import_module(lesson)
        # A paragraph runs until the blank line, so names on wrapped lines count too.
        paragraphs = re.findall(r"\*\*In code:\*\*(.*?)(?:\n\s*\n|\Z)", module.__doc__, re.S)
        cited = [n for p in paragraphs for n in re.findall(r"`([A-Za-z_][\w.]*)(?:\(\))?`", p)]
        # pdoc links a short name only when this module defines it; anything else must be written dotted.
        # It never links private names, so those would be dead ends too.
        source = Path(module.__file__).read_text()

        def defined_here(name: str) -> bool:
            top = name.split(".")[0]
            owner = getattr(getattr(module, top, None), "__module__", None)
            # Plain data (a dict, a list) has no __module__; it is ours if the module assigns it at top level.
            return owner == lesson if owner else re.search(rf"^{re.escape(top)}\s*[:=]", source, re.M) is not None

        broken = [n for n in cited if n.split(".")[-1].startswith("_") or _resolve(module, n) is None
                  or not (n.startswith("primer.") or defined_here(n))]
        assert broken == []

    def test_given_the_readme_each_lesson_row_links_its_page_on_the_live_site(self):
        from primer.curriculum import SITE_URL

        assert f"({SITE_URL}primer/ml/attention.html)" in readme_section()

    def test_given_the_readme_it_says_how_to_clone_the_real_repository(self):
        from primer.curriculum import REPO_URL

        assert f"git clone {REPO_URL}" in (ROOT / "README.md").read_text()


class TestCheckingLinksIntoThisRepository:
    # Links to our own GitHub files are checked against the working tree, so they are verified offline.
    def test_given_a_link_to_lines_that_exist_it_passes(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/primer/ml/attention.py#L1-L3") is None

    def test_given_a_link_pinned_to_a_commit_past_the_end_of_a_file_it_is_reported(self, published):
        from tools.sitecheck import own_repo_problem

        # On GitHub Actions the checkout is that commit, so the working tree is what the link will show.
        url = f"https://github.com/someone/a-fork/blob/{SHA}/LICENSE#L5-L999"
        assert own_repo_problem(url) == "LICENSE has 94 lines, link asks for L5-L999"

    def test_given_a_link_to_a_file_that_does_not_exist_it_is_reported(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/primer/ml/nope.py") == "no such file: primer/ml/nope.py"

    def test_given_a_link_past_the_end_of_a_file_it_is_reported(self):
        from primer.curriculum import REPO_URL
        from tools.sitecheck import own_repo_problem

        assert own_repo_problem(f"{REPO_URL}/blob/main/LICENSE#L5-L999") == "LICENSE has 94 lines, link asks for L5-L999"

    def test_given_an_in_code_line_showing_arguments_or_literals_only_names_are_checked(self):
        from tools.sitecheck import unlinked_code_names

        # criterion="entropy" and {} show how to call something; they aren't names that could link.
        page = '<p><strong>In code:</strong> <code><a href="#tree">tree</a></code> with <code>criterion="entropy"</code> and <code>{}</code>.</p>'
        assert unlinked_code_names(page) == []

    def test_given_an_in_code_line_whose_names_did_not_become_links_it_is_reported(self):
        from tools.sitecheck import unlinked_code_names

        # pdoc puts the link inside the code element.
        page = '<p><strong>In code:</strong> <code><a href="#run">run</a></code> and <code>_helper</code> do it.</p>'
        assert unlinked_code_names(page) == ["_helper"]


class TestPagesThatAreNotLessons:
    def test_given_a_page_that_is_not_a_lesson_its_bar_leads_home_and_to_github(self):
        from primer.curriculum import REPO_URL
        from tools.docsite import site_nav

        nav = site_nav("primer/glossary.html")
        assert 'href="../index.html"' in nav and f'href="{REPO_URL}"' in nav


def _hex_rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))


class TestOneThemeEverywhere:
    THEME_CSS = ROOT / "docs" / "assets" / "theme.css"

    def test_given_dark_mode_the_page_background_is_a_neutral_grey_not_a_navy(self):
        dark = re.search(r':root\[data-theme="dark"\]\s*\{(.*?)\}', self.THEME_CSS.read_text(), re.S).group(1)
        r, g, b = _hex_rgb(re.search(r"--p-bg:\s*(#[0-9a-fA-F]{6})", dark).group(1))
        # Navy is blue well above red and green; a neutral grey keeps the three channels within a few steps.
        assert max(r, g, b) - min(r, g, b) <= 6

    def test_given_the_system_prefers_dark_and_no_choice_was_made_the_same_dark_palette_applies(self):
        css = self.THEME_CSS.read_text()
        forced = re.search(r':root\[data-theme="dark"\]\s*\{(.*?)\}', css, re.S).group(1)
        auto = re.search(r':root:not\(\[data-theme="light"\]\)\s*\{(.*?)\}', css, re.S).group(1)
        assert forced.split() == auto.split()

    def test_given_a_lesson_its_nav_has_the_theme_switcher(self):
        from tools.docsite import lesson_nav

        assert "data-theme-toggle" in lesson_nav("primer.ml.attention")

    def test_given_a_page_that_is_not_a_lesson_its_bar_has_the_theme_switcher(self):
        from tools.docsite import site_nav

        assert "data-theme-toggle" in site_nav("primer/glossary.html")

    def test_given_the_home_page_it_uses_the_shared_theme_and_has_the_switcher(self):
        from tools.docsite import render_home

        home = render_home()
        assert 'href="assets/theme.css"' in home and 'src="assets/theme.js"' in home and "data-theme-toggle" in home

    def test_given_a_pdoc_page_the_theme_loads_in_its_head_so_it_never_flashes_the_wrong_colours(self):
        from tools.docsite import add_theme

        page = add_theme("<html><head><title>x</title></head><body></body></html>", "primer/ml/attention.html")
        head = page.split("</head>")[0]
        assert 'href="../../assets/theme.css"' in head and 'src="../../assets/theme.js"' in head

    @pytest.mark.parametrize("companion", sorted(p.name for p in (ROOT / "docs" / "papers").glob("*.html")))
    def test_given_a_paper_companion_it_uses_the_shared_theme(self, companion):
        head = (ROOT / "docs" / "papers" / companion).read_text().split("</head>")[0]
        assert 'href="../assets/theme.css"' in head and 'src="../assets/theme.js"' in head


class TestNoPageRepeatsTheHomePage:
    # pdoc makes a page for each package, but a package's page would only repeat the reading list the
    # home page already shows, so each one forwards to that section of the home page instead.

    def test_given_the_package_pages_each_forwards_to_the_home_page_section_listing_its_lessons(self):
        from tools.docsite import package_forwards

        assert package_forwards() == {
            "primer.html": "index.html#lessons",
            "primer/ml.html": "../index.html#ml",
            "primer/ml/embeddings.html": "../../index.html#embeddings",
            "primer/ml/generative.html": "../../index.html#generative",
            "primer/agents.html": "../index.html#agents",
        }

    def test_given_a_forwarded_page_it_still_offers_a_plain_link_for_browsers_that_do_not_redirect(self):
        from tools.docsite import forward_page

        page = forward_page("../index.html#ml")
        assert 'http-equiv="refresh" content="0; url=../index.html#ml"' in page and 'href="../index.html#ml"' in page

    def test_given_the_home_page_every_section_a_package_forwards_to_exists(self):
        from tools.docsite import package_forwards, render_home

        home = render_home()
        anchors = {target.split("#")[1] for target in package_forwards().values()}
        assert [a for a in anchors if f'id="{a}"' not in home] == []

    def test_given_the_home_page_it_no_longer_sends_readers_to_the_package_overview(self):
        from tools.docsite import render_home

        assert 'href="primer.html"' not in render_home()

    def test_given_pdocs_links_to_a_package_page_they_go_straight_to_the_home_page_instead(self):
        from tools.docsite import skip_forwarded_pages

        # pdoc's title and sidebar link each lesson to its package pages.
        page = '<a href="./../../../primer.html">primer</a>.<a href="./../../ml.html">ml</a> <a href="../embeddings.html">up</a>'
        linked = skip_forwarded_pages(page, "primer/ml/embeddings/ann.html")
        assert linked == ('<a href="../../../index.html#lessons">primer</a>.<a href="../../../index.html#ml">ml</a> '
                          '<a href="../../../index.html#embeddings">up</a>')

    def test_given_a_link_to_a_lesson_it_is_left_alone(self):
        from tools.docsite import skip_forwarded_pages

        page = '<a href="../attention.html#softmax">softmax</a>'
        assert skip_forwarded_pages(page, "primer/ml/transformer.html") == page


class TestTheHomePageOrder:
    def test_given_the_home_page_the_lessons_come_first_then_the_big_questions_then_the_papers(self):
        from tools.docsite import render_home

        home = render_home()
        positions = [home.index(f'id="{anchor}"') for anchor in ("lessons", "agents", "big", "papers")]
        assert positions == sorted(positions)


def _committed_markdown() -> list[str]:
    import subprocess

    return subprocess.run(["git", "ls-files", "*.md"], cwd=ROOT, capture_output=True, text=True).stdout.split()


class TestModuleNamesOnGitHub:
    # GitHub renders Markdown but not docstrings, so a module named in a .md file must be a link to its file.

    def test_given_a_module_name_in_markdown_it_becomes_a_link_to_its_file(self):
        from primer.curriculum import link_code_references

        assert link_code_references("See `primer.agents.llm`.", "docs") == "See [`primer.agents.llm`](../primer/agents/llm.py)."

    def test_given_a_name_inside_a_module_the_link_goes_to_the_module_that_defines_it(self):
        from primer.curriculum import link_code_references

        text = "The adapter (`primer.agents.llm.ClaudeLLM`)."
        assert link_code_references(text, ".") == "The adapter ([`primer.agents.llm.ClaudeLLM`](primer/agents/llm.py))."

    def test_given_a_package_name_the_link_goes_to_its_init_file(self):
        from primer.curriculum import link_code_references

        assert link_code_references("`primer.common`", ".") == "[`primer.common`](primer/common/__init__.py)"

    def test_given_a_name_that_is_already_a_link_it_is_left_alone(self):
        from primer.curriculum import link_code_references

        text = "From [`primer.agents.llm`](../primer/agents/llm.py)."
        assert link_code_references(text, "docs") == text

    def test_given_a_name_in_a_fenced_code_block_it_is_left_alone(self):
        from primer.curriculum import link_code_references

        text = "```\n`primer.agents.llm`\n```"
        assert link_code_references(text, ".") == text

    def test_given_a_path_to_a_committed_file_it_becomes_a_link_to_that_file(self):
        from primer.curriculum import link_code_references

        # Paths in the docs are written from the repository root, wherever the Markdown file sits.
        text = "Edit `primer/glossary.py`, then see `CLAUDE.md`."
        assert link_code_references(text, "docs/papers") == (
            "Edit [`primer/glossary.py`](../../primer/glossary.py), then see [`CLAUDE.md`](../../CLAUDE.md).")

    def test_given_a_path_to_build_output_that_is_not_committed_it_stays_plain(self):
        from primer.curriculum import link_code_references

        assert link_code_references("open `docs/html/index.html`", ".") == "open `docs/html/index.html`"

    def test_given_a_run_command_the_whole_command_links_to_the_lesson_it_runs(self):
        from primer.curriculum import link_code_references

        text = "`python -m primer.ml.attention` runs a lesson"
        assert link_code_references(text, ".") == "[`python -m primer.ml.attention`](primer/ml/attention.py) runs a lesson"

    def test_given_a_class_defined_in_exactly_one_module_it_links_to_that_module(self):
        from primer.curriculum import link_code_references

        assert link_code_references("the `ScriptedLLM`", ".") == "the [`ScriptedLLM`](primer/agents/llm.py)"

    def test_given_a_word_that_is_not_code_in_this_repository_it_stays_plain(self):
        from primer.curriculum import link_code_references

        assert link_code_references("`make readme` and `numpy`", ".") == "`make readme` and `numpy`"

    @pytest.mark.parametrize("markdown", _committed_markdown())
    def test_given_a_markdown_file_it_names_no_lesson_in_plain_text(self, markdown):
        text = re.sub(r"```.*?```", "", (ROOT / markdown).read_text(), flags=re.S)
        prose = re.sub(r"\[[^\]]*\]\([^)]*\)", "", text)
        # Short lesson names like ml.embeddings.word2vec, outside any link.
        assert re.findall(r"(?<![\w/.`])(?:ml|agents)\.(?:embeddings\.)?[a-z_]+\b", prose) == []

    @pytest.mark.parametrize("markdown", _committed_markdown())
    def test_given_a_markdown_file_every_module_it_names_is_a_link_github_can_follow(self, markdown):
        from primer.curriculum import link_code_references

        text = (ROOT / markdown).read_text()
        assert link_code_references(text, str(Path(markdown).parent)) == text


def _line_inside(path: str, outer: str, inner: str) -> int:
    """The line of `inner` after the line starting `outer`, read straight from the file."""
    lines = (ROOT / path).read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(outer))
    return next(i for i, line in enumerate(lines[start:], start + 1) if line.startswith(inner))


class TestNoCodeMentionIsLeftUnlinked:
    # Anything on a page that names code in this repository is a link: public members to their entry,
    # everything else (dunder methods, private classes) to its lines, a lesson's own name to its code.

    def test_given_a_lessons_run_command_the_module_name_links_to_its_code(self, local):
        from tools.docsite import link_code_mentions

        page = "<p>Run: <code>python -m primer.ml.embeddings.word2vec</code></p>"
        linked = link_code_mentions(page, "primer.ml.embeddings.word2vec", "primer/ml/embeddings/word2vec.html")
        # docs/html/primer/ml/embeddings/ is five folders below the repository root.
        assert '<code>python -m <a href="../../../../../primer/ml/embeddings/word2vec.py">primer.ml.embeddings.word2vec</a></code>' in linked

    def test_given_a_lessons_title_its_own_name_links_to_its_code(self, local):
        from tools.docsite import link_code_mentions

        page = '<h1 class="modulename">\n<a href="../ml.html">ml</a><wbr>.<a href="../embeddings.html">embeddings</a><wbr>.word2vec    </h1>'
        linked = link_code_mentions(page, "primer.ml.embeddings.word2vec", "primer/ml/embeddings/word2vec.html")
        assert '<wbr>.<a href="../../../../../primer/ml/embeddings/word2vec.py">word2vec</a>' in linked

    def test_given_a_short_name_imported_from_another_lesson_it_links_to_that_lessons_entry(self, local):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p><code>LLM.complete</code></p>", "primer.agents.agent_loop", "primer/agents/agent_loop.html")
        assert '<code><a href="llm.html#LLM.complete">LLM.complete</a></code>' in linked

    def test_given_a_dunder_method_it_links_to_its_exact_lines(self, published):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p><code>TinyGPT.__call__</code></p>", "primer.ml.transformer", "primer/ml/transformer.html")
        line = _line_inside("primer/ml/transformer.py", "class TinyGPT", "    def __call__(")
        assert f"/blob/{SHA}/primer/ml/transformer.py#L{line}-L" in linked

    def test_given_a_private_class_in_a_signature_it_links_to_its_exact_lines(self, published):
        from tools.docsite import link_code_mentions

        page = '<span class="return-annotation">: list[primer.agents.cost._Entry]</span>'
        linked = link_code_mentions(page, "primer.agents.cost", "primer/agents/cost.html")
        line = _first_line_of("primer/agents/cost.py", "class _Entry")
        # The range starts at the class's decorator, if it has one, so it must contain the class line.
        first, last = map(int, re.search(rf"/blob/{SHA}/primer/agents/cost\.py#L(\d+)-L(\d+)", linked).groups())
        assert first <= line <= last and ">primer.agents.cost._Entry</a>" in linked

    def test_given_code_that_names_nothing_in_the_repository_it_is_left_alone(self, local):
        from tools.docsite import link_code_mentions

        page = "<p><code>n_heads</code> and <code>np.exp</code></p>"
        assert link_code_mentions(page, "primer.ml.attention", "primer/ml/attention.html") == page

    def test_given_a_source_listing_it_is_left_alone(self, local):
        from tools.docsite import link_code_mentions

        page = "<pre><code>TinyGPT.__call__</code></pre>"
        assert link_code_mentions(page, "primer.ml.transformer", "primer/ml/transformer.html") == page

    def test_given_a_name_that_is_already_a_link_it_is_left_alone(self, local):
        from tools.docsite import link_code_mentions

        page = '<p><code><a href="llm.html#LLM">LLM</a></code></p>'
        assert link_code_mentions(page, "primer.agents.agent_loop", "primer/agents/agent_loop.html") == page

    def test_given_a_page_with_an_unlinked_mention_the_site_check_reports_it(self, local):
        from tools.sitecheck import unlinked_code_mentions

        assert unlinked_code_mentions("<p><code>LLM</code></p>", "primer.agents.agent_loop") == ["LLM"]

    def test_given_a_path_to_a_committed_file_it_links_to_that_file(self, local):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p><code>primer/glossary.py</code></p>", "primer.curriculum", "primer/curriculum.html")
        assert '<code><a href="../../../primer/glossary.py">primer/glossary.py</a></code>' in linked


class TestEveryAnchorExists:
    def test_given_a_link_to_an_anchor_the_page_does_not_have_it_is_reported(self, tmp_path):
        from tools.sitecheck import missing_anchors

        (tmp_path / "a.html").write_text('<a href="b.html#there">x</a> <a href="b.html#nowhere">y</a> <a href="#here">z</a><p id="here"></p>')
        (tmp_path / "b.html").write_text('<section id="there"></section>')
        assert missing_anchors(tmp_path) == {"a.html": {"b.html#nowhere"}}

    def test_given_pdoc_links_to_a_private_class_it_does_not_document_the_link_goes_to_its_lines(self, published):
        from tools.docsite import link_code_mentions

        # pdoc names private base classes in "inherited members" but gives them no entry to land on.
        page = '<a href="#_Index.dim">dim</a>'
        linked = link_code_mentions(page, "primer.ml.embeddings.ann", "primer/ml/embeddings/ann.html")
        assert f"/blob/{SHA}/primer/ml/embeddings/ann.py#L" in linked


class TestNamesWrittenWithoutTheirModule:
    def test_given_a_class_defined_in_exactly_one_other_module_it_links_to_that_classs_entry(self, local):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p><code>ClaudeLLM</code></p>", "primer.agents.evals", "primer/agents/evals.html")
        assert '<code><a href="llm.html#ClaudeLLM">ClaudeLLM</a></code>' in linked

    def test_given_a_class_name_two_modules_define_the_site_check_reports_it_for_the_author_to_qualify(self, local):
        from tools.sitecheck import unlinked_code_mentions

        # SemanticCache exists in both the cost lesson and the clustering lesson; only the author knows which.
        assert unlinked_code_mentions("<p><code>SemanticCache</code></p>", "primer.agents.evals") == ["SemanticCache"]

    def test_given_a_parameter_that_shares_a_functions_name_the_site_check_leaves_it_alone(self, local):
        from tools.sitecheck import unlinked_code_mentions

        assert unlinked_code_mentions("<p><code>answer</code></p>", "primer.agents.evals") == []


class TestNoLinkGoesNowhere:
    def test_given_pdocs_empty_link_to_the_page_itself_it_leads_to_the_lessons_code(self, local):
        from tools.docsite import link_code_mentions

        # pdoc links a module named on its own page with href="", which just reloads the page.
        page = '<p>Run: <code>python -m <a href="">primer.ml.embeddings.word2vec</a></code></p>'
        linked = link_code_mentions(page, "primer.ml.embeddings.word2vec", "primer/ml/embeddings/word2vec.html")
        assert '<a href="../../../../../primer/ml/embeddings/word2vec.py">primer.ml.embeddings.word2vec</a>' in linked

    def test_given_a_link_with_an_empty_address_the_site_check_reports_it(self, tmp_path):
        from tools.sitecheck import empty_links

        (tmp_path / "a.html").write_text('<a href="">here</a> <a href="b.html">fine</a>')
        assert empty_links(tmp_path) == {"a.html": ["here"]}


class TestTheHomePageKeepsEachPartsIntroduction:
    # The package pages forward to the home page, so the home page carries what they said.

    def test_given_the_embeddings_part_its_section_explains_what_an_embedding_is(self):
        from tools.docsite import render_home

        section = render_home().split('id="embeddings"')[1].split("</section>")[0]
        assert "closeness in space means similarity in meaning" in section

    def test_given_the_agents_part_its_section_says_everything_runs_offline_with_links_to_both_models(self):
        from tools.docsite import render_home

        section = render_home().split('id="agents"')[1].split("</section>")[0]
        assert "runs offline" in section
        assert 'href="primer/agents/llm.html#ScriptedLLM"' in section and 'href="primer/agents/llm.html#ClaudeLLM"' in section

    def test_given_the_home_page_it_says_where_the_shared_code_lives(self):
        from tools.docsite import render_home

        assert 'href="primer/common.html"' in render_home()

    def test_given_any_part_its_section_never_says_the_same_sentence_twice(self):
        from primer.curriculum import PARTS
        from tools.docsite import render_home

        home = render_home()
        for part in PARTS:
            section = home.split(f'id="{part.key}"')[1].split("</section>")[0]
            # The prose after the heading (which has no full stop), with tags turned to spaces so sentences don't glue.
            prose = section.split("</h2>", 1)[1].split('<ol class="cards">')[0]
            text = " ".join(re.sub(r"<[^>]+>", " ", prose).split())
            sentences = [s.strip() for s in re.split(r"(?<=\.)\s+", text) if s.strip()]
            assert len(sentences) == len(set(sentences)), part.key


# A small collected suite, in pytest's "path::Class::test[param]" form, so these specs don't run pytest.
_FAKE_SUITE = [
    "tests/test_attention.py::TestCausalMasking::test_given_a_causal_mask_future_tokens_receive_zero_attention",
    "tests/test_attention.py::TestSoftmax::test_given_equal_scores_attention_is_shared_equally[2]",
    "tests/test_attention.py::TestSoftmax::test_given_equal_scores_attention_is_shared_equally[3]",
    "tests/test_navigation.py::TestTheCurriculum::test_given_the_curriculum_no_lesson_appears_twice",
]


class TestTheSpecificationIsPublished:
    # The suite is behaviour-driven and written test-first; the site shows it as the readable spec it is.

    def test_given_a_collected_suite_each_lesson_is_counted_by_its_own_test_file(self):
        from tools.docsite import tests_per_file

        assert tests_per_file(_FAKE_SUITE) == {"tests/test_attention.py": 3, "tests/test_navigation.py": 1}

    def test_given_the_spec_page_each_behaviour_reads_as_a_sentence_under_its_lesson(self, local):
        from tools.docsite import spec_page

        page = spec_page(_FAKE_SUITE)
        lesson = page.split('id="primer.ml.attention"')[1].split("</section>")[0]
        assert "given a causal mask future tokens receive zero attention" in lesson and "causal masking" in lesson

    def test_given_a_parametrised_test_the_spec_page_lists_its_behaviour_once(self, local):
        from tools.docsite import spec_page

        assert spec_page(_FAKE_SUITE).count("given equal scores attention is shared equally") == 1

    def test_given_a_behaviour_on_the_spec_page_it_links_to_the_exact_lines_of_the_test_that_checks_it(self, published):
        from tools.docsite import spec_page

        line = _line_inside("tests/test_attention.py", "class TestCausalMasking", "    def test_given_a_causal_mask")
        assert f"/blob/{SHA}/tests/test_attention.py#L{line}-L" in spec_page(_FAKE_SUITE)

    def test_given_the_spec_page_each_lesson_section_links_to_the_lesson(self, local):
        from tools.docsite import spec_page

        lesson = spec_page(_FAKE_SUITE).split('id="primer.ml.attention"')[1].split("</section>")[0]
        assert 'href="primer/ml/attention.html"' in lesson

    def test_given_a_test_count_the_lesson_nav_says_how_many_tests_specify_it_and_links_to_them(self):
        from tools.docsite import lesson_nav

        nav = lesson_nav("primer.ml.attention", tests=32)
        assert '<a href="../../spec.html#primer.ml.attention">32 tests</a>' in nav

    def test_given_a_test_count_the_home_page_states_it_and_links_to_the_specification(self):
        from tools.docsite import render_home

        header = render_home(tests=1200).split("</header>")[0]
        assert "1,200 tests" in header and 'href="spec.html"' in header

    def test_given_a_site_that_states_a_different_count_from_the_suite_the_site_check_reports_it(self, tmp_path, monkeypatch):
        import tools.docsite
        from tools.sitecheck import spec_count_problems

        monkeypatch.setattr(tools.docsite, "collect_tests", lambda: _FAKE_SUITE)  # a suite of 4
        (tmp_path / "spec.html").write_text("<h1>The specification: 4 tests</h1>")
        (tmp_path / "index.html").write_text("pinned down by a suite of 1,200 tests")
        assert spec_count_problems(tmp_path) == ["index.html states ['1,200'], the suite has 4"]


class TestNothingRendersBroken:
    def test_given_indented_lines_that_collapsed_into_one_paragraph_the_site_check_reports_them(self):
        from tools.sitecheck import collapsed_blocks

        page = "<p>scheme:\n    \"none\": embeddings only\n    \"rope\": rotate q and k</p><pre>  indented is fine here</pre>"
        assert collapsed_blocks(page) == ['scheme: "none": embeddings only "rope": rotate q and k']

    def test_given_markdown_left_raw_in_rendered_text_the_site_check_reports_it(self):
        from tools.sitecheck import raw_markdown

        page = "<li>Vaswani et al., *Attention Is All You Need* (2017)</li><p>fine: 2 * 3 * 4</p><code>*args</code>"
        assert raw_markdown(page) == ["*Attention Is All You Need*"]

    def test_given_two_prices_in_one_paragraph_the_site_check_reports_them_typeset_as_math(self):
        from tools.sitecheck import prices_typeset_as_math

        # MathJax pairs the two dollar signs and runs "per million input tokens" together in italics.
        page = ("<p>at $2 per million input tokens and $4 for the tuned one</p>"
                "<p>fine: \\$2 and \\$4, and $x_i$ and $2^{10}$</p><td>$0.02 =\n<strong>$500</strong></td>")
        assert prices_typeset_as_math(page) == ["$2 per million input tokens and $", "$0.02 =\n$"]

    def test_given_the_home_page_paper_titles_render_their_emphasis(self):
        from tools.docsite import render_home

        home = render_home()
        assert "<em>Attention Is All You Need</em>" in home and "*Attention Is All You Need*" not in home

    def test_given_a_heading_that_skips_a_level_the_site_check_reports_it(self):
        from tools.sitecheck import heading_skips

        # Screen readers and outlines navigate by heading level; h2 -> h4 leaves a hole.
        page = "<h1>A</h1><h2>B</h2><h4>Everyday picture</h4><h3>C</h3><h4>fine</h4>"
        assert heading_skips(page) == ["h2 -> h4: Everyday picture"]

    def test_given_pdocs_section_labels_they_become_labels_not_headings_that_skip_levels(self):
        from tools.docsite import label_sections

        page = '<h2>Title</h2><h6 id="arguments">Arguments:</h6><ul></ul><h5>Inherited Members</h5>'
        assert label_sections(page) == ('<h2>Title</h2><p class="doc-label" id="arguments"><strong>Arguments:</strong></p><ul></ul>'
                                        '<p class="doc-label"><strong>Inherited Members</strong></p>')

    @pytest.mark.parametrize("companion", sorted(p.name for p in (ROOT / "docs" / "papers").glob("*.html")))
    def test_given_a_companion_its_headings_never_skip_a_level(self, companion):
        from tools.sitecheck import heading_skips

        assert heading_skips((ROOT / "docs" / "papers" / companion).read_text()) == []


class TestEveryWayOfNamingCodeIsLinked:
    def test_given_a_call_written_with_its_arguments_the_function_name_links(self, local):
        from tools.docsite import link_code_mentions

        page = "<p><code>plan_and_execute(planner, goal)</code></p>"
        linked = link_code_mentions(page, "primer.agents.planning", "primer/agents/planning.html")
        assert '<code><a href="#plan_and_execute">plan_and_execute</a>(planner, goal)</code>' in linked

    def test_given_a_field_named_without_its_class_it_links_to_the_one_class_on_the_page_that_has_it(self, local):
        from tools.docsite import link_code_mentions

        page = '<p><code>stop_cause</code></p><div id="AgentResult.stop_cause"></div>'
        linked = link_code_mentions(page, "primer.agents.agent_loop", "primer/agents/agent_loop.html")
        assert '<code><a href="#AgentResult.stop_cause">stop_cause</a></code>' in linked

    def test_given_a_field_two_classes_on_the_page_share_the_site_check_reports_it(self, local):
        from tools.sitecheck import unlinked_code_mentions

        page = '<p><code>name</code></p><div id="Tool.name"></div><div id="Skill.name"></div>'
        assert unlinked_code_mentions(page, "primer.agents.tools") == ["name"]

    def test_given_a_function_named_in_plain_prose_it_links(self, local):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p>Compare with info_nce's analytic gradients.</p>", "primer.ml.losses", "primer/ml/losses.html")
        assert '<a href="#info_nce">info_nce</a>\'s analytic gradients' in linked

    def test_given_a_class_named_in_plain_prose_it_links(self, local):
        from tools.docsite import link_code_mentions

        linked = link_code_mentions("<p>Run it on an untrained TinyGPT.</p>", "primer.ml.big_picture", "primer/ml/big_picture.html")
        assert '<a href="transformer.html#TinyGPT">TinyGPT</a>' in linked  # both pages sit in primer/ml/

    def test_given_math_that_happens_to_contain_a_name_it_is_left_alone(self, local):
        from tools.docsite import link_code_mentions

        page = "<p>$$\\text{info_nce} = -\\log p$$ and $d_k$</p>"
        assert link_code_mentions(page, "primer.ml.losses", "primer/ml/losses.html") == page

    def test_given_code_that_names_a_function_that_does_not_exist_the_site_check_reports_it(self, local):
        from tools.sitecheck import nonexistent_code

        # A companion once pointed readers at hyde(); the function is hyde_search.
        assert nonexistent_code("<p>The code is <code>hyde()</code>; see <code>len(x)</code>.</p>", "primer") == ["hyde()"]

    def test_given_a_functions_own_parameter_in_its_docstring_it_is_not_taken_for_a_field(self, local):
        from tools.sitecheck import unlinked_code_mentions

        # near_duplicates takes `threshold`; Router and SemanticCache also have a `threshold` field.
        page = ('<section id="near_duplicates"><div class="docstring"><p>Pairs at least <code>threshold</code> apart.</p></div></section>'
                '<div id="Router.threshold"></div><div id="SemanticCache.threshold"></div>')
        assert unlinked_code_mentions(page, "primer.ml.embeddings.clustering") == []

    def test_given_a_signature_or_default_value_only_fully_dotted_names_in_it_link(self, local):
        from tools.docsite import link_code_mentions

        page = ('<span class="signature">(tool_output: int = 8000) -> primer.agents.cost._Entry</span>'
                "<span class=\"default_value\">[{'name': 'search_kb'}]</span>")
        linked = link_code_mentions(page, "primer.agents.cost", "primer/agents/cost.html")
        assert ">tool_output<" not in linked and "'search_kb'" in linked and ">primer.agents.cost._Entry</a>" in linked

    def test_given_prose_after_a_signature_names_in_it_still_link(self, local):
        from tools.docsite import link_code_mentions

        page = '<span class="signature">(x)</span><p>Run it on an untrained TinyGPT.</p>'
        linked = link_code_mentions(page, "primer.ml.big_picture", "primer/ml/big_picture.html")
        assert '<a href="transformer.html#TinyGPT">TinyGPT</a>' in linked


class TestTheSameThingLooksTheSameEverywhere:
    def test_given_any_bar_or_page_the_repository_link_reads_code_on_github(self):
        from tools.docsite import lesson_nav, render_home, site_nav

        for html in (lesson_nav("primer.ml.attention"), site_nav("primer/glossary.html"), render_home()):
            assert ">Code on GitHub</a>" in html and ">GitHub</a>" not in html and ">Source on GitHub</a>" not in html

    def test_given_the_companion_bar_it_names_the_repository_link_the_same_way(self):
        assert "Code on GitHub" in (ROOT / "docs/papers/assets/papers.js").read_text()

    def test_given_the_companion_bar_it_links_the_notation_lesson_like_every_other_bar(self):
        assert 'primer/notation.html">Notation</a>' in (ROOT / "docs/papers/assets/papers.js").read_text()

    def test_given_the_catalog_script_it_gives_companions_each_lessons_title(self):
        from tools.docsite import catalog_js

        # Companions name a lesson by its title, as the home page does, not by its module path.
        assert '"primer.ml.attention": "Attention"' in catalog_js()

    def test_given_the_companion_script_it_names_lessons_by_title(self):
        js = (ROOT / "docs/papers/assets/papers.js").read_text()
        assert "PRIMER_LESSONS" in js


class TestEveryPageCanBeReached:
    def test_given_a_page_no_other_page_links_to_the_site_check_reports_it(self, tmp_path):
        from tools.sitecheck import orphan_pages

        (tmp_path / "index.html").write_text('<a href="a.html">a</a>')
        (tmp_path / "a.html").write_text('<a href="index.html">home</a>')
        (tmp_path / "lost.html").write_text("")
        assert orphan_pages(tmp_path) == ["lost.html"]

    def test_given_the_home_page_it_links_the_map_the_site_is_generated_from(self):
        from tools.docsite import render_home

        assert 'href="primer/curriculum.html"' in render_home()


class TestCompanionLinks:
    # Companions write lesson links as data for their script, so a normal crawl never sees them.

    def test_given_a_companion_whose_script_links_a_lesson_that_does_not_exist_it_is_reported(self, tmp_path):
        from tools.sitecheck import broken_companion_lessons

        # Companions write lesson links as data for their script, so a normal crawl never sees them.
        (tmp_path / "papers").mkdir()
        (tmp_path / "primer").mkdir()
        (tmp_path / "primer" / "real.html").write_text("")
        (tmp_path / "papers" / "p.html").write_text('<a data-lesson="primer/real.html">a</a> <a data-lesson="primer/gone.html">b</a>')
        assert broken_companion_lessons(tmp_path) == {"p.html": {"primer/gone.html"}}

    def test_given_a_companion_whose_script_links_a_forwarding_page_the_site_check_reports_it(self, tmp_path):
        from tools.sitecheck import links_through_forwards

        (tmp_path / "papers").mkdir()
        (tmp_path / "primer.html").write_text('<meta http-equiv="refresh" content="0; url=index.html#lessons">')
        (tmp_path / "papers" / "p.html").write_text('<a data-lesson="primer.html">The primer</a>')
        assert links_through_forwards(tmp_path) == {"papers/p.html": {"primer.html"}}


class TestTheHomePageHeader:
    # The first thing a reader sees: what this is, where the code lives, and how it is checked.

    def test_given_the_home_page_its_header_shows_the_repositorys_address_as_a_link(self):
        from primer.curriculum import REPO_URL
        from tools.docsite import render_home

        header = render_home().split("</header>")[0]
        # Written out in full, so a reader sees exactly where the code lives.
        assert f'<a href="{REPO_URL}">{REPO_URL}</a>' in header

    def test_given_the_home_page_the_example_run_command_links_to_the_code_it_runs(self, local):
        from tools.docsite import render_home

        # A run command links to the code it runs, on every page.
        assert '<code>python -m <a href="../../primer/ml/attention.py">primer.ml.attention</a></code>' in render_home()

    def test_given_the_home_page_it_says_what_a_test_is_and_shows_a_real_one(self, local):
        from tools.docsite import render_home

        header = render_home().split("</header>")[0]
        assert "checked by a test." not in header  # jargon: says nothing to someone who doesn't write tests
        # The example it quotes must be a real test, and the link must lead to the file that holds it.
        assert "given a causal mask, future tokens receive zero attention" in header
        assert "def test_given_a_causal_mask_future_tokens_receive_zero_attention" in (ROOT / "tests/test_attention.py").read_text()
        assert 'href="../../tests/test_attention.py"' in header

    def test_given_lessons_numbered_from_zero_the_home_page_and_breadcrumbs_agree(self):
        from tools.docsite import lesson_nav, render_home

        # Numbered from 0: say both the count and the range, so "Lesson 5 of 0 to 53" and "54 lessons" agree.
        from primer.curriculum import CURRICULUM

        n = len(CURRICULUM)
        assert f"{n} lessons, numbered 0 to {n - 1}" in render_home()
        assert f"Lesson 5 of 0 to {n - 1}" in lesson_nav("primer.ml.attention")


class TestDiagramsDrawOnce:
    # Mermaid names each diagram after the clock; two drawn in the same millisecond share a name and draw on
    # top of each other. pdoc's script also redraws them whenever the page changes, which mermaid itself does.

    PDOC_SCRIPT = ('<script type="module" defer>\n    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";\n'
                   '    document.addEventListener("DOMContentLoaded", () => {\n'
                   '        new MutationObserver(() => mermaid.run()).observe(document.body, {childList: true});\n    })\n</script>')

    def test_given_a_page_with_diagrams_each_is_drawn_once_in_order_under_its_own_name(self):
        from tools.docsite import draw_diagrams_once

        page = draw_diagrams_once(f"<head>{self.PDOC_SCRIPT}</head>")
        assert "startOnLoad: false" in page and "diagram-${i + 1}" in page

    def test_given_a_page_with_diagrams_nothing_redraws_them_when_the_page_changes(self):
        from tools.docsite import draw_diagrams_once

        assert "MutationObserver" not in draw_diagrams_once(f"<head>{self.PDOC_SCRIPT}</head>")

    def test_given_a_built_page_whose_diagrams_start_automatically_the_site_check_reports_it(self, tmp_path):
        from tools.sitecheck import diagram_problems

        (tmp_path / "a.html").write_text('<div class="mermaid">flowchart LR</div><script>mermaid.run()</script>')
        (tmp_path / "b.html").write_text('<div class="mermaid">flowchart LR</div><script>mermaid.initialize({ startOnLoad: false })</script>')
        assert diagram_problems(tmp_path) == ["a.html"]


class TestEveryPageFitsAPhone:
    # tools/browsercheck.py loads every page at 390px in headless Chrome; these specify what it counts as a problem.

    def test_given_a_page_wider_than_the_screen_it_is_reported(self):
        from tools.browsercheck import too_wide

        results = [{"page": "a.html", "width": 968, "screen": 390, "wide": ["mjx-container: ..."]},
                   {"page": "b.html", "width": 390, "screen": 390, "wide": []}]
        assert [r["page"] for r in too_wide(results)] == ["a.html"]

    def test_given_a_site_its_forwarding_stubs_are_not_checked(self, tmp_path):
        from tools.browsercheck import pages_to_check

        # They show nothing: the browser moves straight on to the home page.
        (tmp_path / "index.html").write_text("<h1>primer</h1>")
        (tmp_path / "primer.html").write_text('<meta http-equiv="refresh" content="0; url=index.html">')
        assert pages_to_check(tmp_path) == ["index.html"]


class TestEveryPageWorksWithAKeyboardAndAScreenReader:
    # tools/browsercheck.py runs these checks inside each loaded page; this specifies what it reports.

    def test_given_pages_with_barriers_only_those_are_reported(self):
        from tools.browsercheck import accessibility_problems

        results = [{"page": "a.html", "a11y": ["image without alt text: x.svg"]}, {"page": "b.html", "a11y": []}]
        assert [r["page"] for r in accessibility_problems(results)] == ["a.html"]


class TestEveryPageRunsItsScriptsCleanly:
    # Headless Chrome writes each page's console to stderr; tools/browsercheck.py reads the problems out of it.
    LOG = (
        '[1:2:0927/091831.9:INFO:CONSOLE:1] "Uncaught ReferenceError: draw is not defined", '
        "source: http://127.0.0.1:8765/papers/gans.html (412)\n"
        '[1:2:0927/091831.9:INFO:CONSOLE:9] "papers.js: symbols with no note on gans: Dstar", '
        "source: http://127.0.0.1:8765/papers/assets/papers.js (941)\n"
        '[1:2:0927/091831.9:INFO:CONSOLE:3] "theme: dark", source: http://127.0.0.1:8765/index.html (3)\n'
    )

    def test_given_a_page_that_throws_the_error_is_reported_against_that_page(self):
        from tools.browsercheck import console_problems

        assert console_problems(self.LOG)["papers/gans.html"] == ["Uncaught ReferenceError: draw is not defined"]

    def test_given_a_companion_warning_about_its_own_markup_it_is_reported(self):
        from tools.browsercheck import console_problems

        # The shared script logs it, so the source names papers.js and the message names the page.
        assert "papers.js: symbols with no note on gans: Dstar" in console_problems(self.LOG)["papers/assets/papers.js"]

    def test_given_an_error_whose_message_spans_several_lines_it_is_reported(self):
        from tools.browsercheck import console_problems

        # Mermaid's parse errors quote the offending line and a caret underneath it.
        log = ('[1:2:0927/131611.6:INFO:CONSOLE:9] "Uncaught Error: Parse error on line 4:\n'
               '...RK[recall@k<br/>\n----------------------^\nExpecting \'SQE\'", '
               "source: http://127.0.0.1:8803/primer/ml/metrics.html (9)\n")
        assert console_problems(log)["primer/ml/metrics.html"][0].startswith("Uncaught Error: Parse error on line 4:")

    def test_given_the_diagram_script_one_broken_diagram_does_not_stop_the_rest(self):
        from tools.docsite import DIAGRAM_SCRIPT

        # A parse error used to end the loop, leaving every later diagram on the page undrawn.
        assert "try {" in DIAGRAM_SCRIPT and "catch" in DIAGRAM_SCRIPT

    def test_given_the_diagram_script_a_broken_diagram_is_reported_as_an_error(self):
        from tools.docsite import DIAGRAM_SCRIPT

        assert 'console.error("Uncaught diagram error' in DIAGRAM_SCRIPT

    def test_given_the_browser_probe_it_reports_every_diagram_that_did_not_draw(self):
        from tools.browsercheck import PROBE_PAGE

        assert '"diagram " + (n + 1) + " did not draw"' in PROBE_PAGE

    def test_given_an_ordinary_log_line_nothing_is_reported(self):
        from tools.browsercheck import console_problems

        assert "index.html" not in console_problems(self.LOG)

    def test_given_the_companion_script_it_warns_about_symbols_and_blocks_with_no_note(self):
        script = (ROOT / "docs" / "papers" / "assets" / "papers.js").read_text()

        # A symbol or diagram part with no note shows "No note yet" only when hovered, which no check would see.
        assert "symbols with no note on " in script and "diagram parts with no note on " in script

    def test_given_the_companion_script_it_names_undefined_glossary_keys_in_words(self):
        script = (ROOT / "docs" / "papers" / "assets" / "papers.js").read_text()

        # Logged as text, not an array object, so the browser check can read the keys.
        assert "glossary keys with no definition on " in script and 'missing.join(", ")' in script

    def test_given_the_glossary_script_a_focused_term_is_described_by_its_definition(self):
        from tools.docsite import TOOLTIP_ASSETS

        assert "setAttribute('aria-describedby','gl-tip')" in TOOLTIP_ASSETS and "el.after(tip)" in TOOLTIP_ASSETS

    def test_given_the_diagram_script_each_diagram_is_named_and_described_by_its_reading(self):
        from tools.docsite import DIAGRAM_SCRIPT

        assert 'setAttribute("role", "img")' in DIAGRAM_SCRIPT and 'setAttribute("aria-describedby"' in DIAGRAM_SCRIPT


class TestTheTitle:
    def test_given_the_home_page_it_is_called_ai_primer(self):
        from tools.docsite import render_home

        home = render_home()
        assert "<title>AI Primer</title>" in home and "<h1>AI Primer</h1>" in home

    def test_given_the_readme_it_opens_with_the_title_and_says_nothing_about_its_author(self):
        # The primer is about the ideas, not the person who wrote it.
        opening = (ROOT / "README.md").read_text().split("## ")[0]
        first_person = re.findall(r"\b(?:I|me|my|I've|I'm)\b", opening)
        assert opening.startswith("# AI Primer\n") and first_person == []

    def test_given_every_bar_and_footer_the_old_title_is_gone(self):
        from tools.docsite import lesson_nav, site_nav

        texts = [lesson_nav("primer.ml.attention"), site_nav("primer/glossary.html"),
                 (ROOT / "tools" / "docsite.py").read_text(), (ROOT / "docs" / "papers" / "assets" / "papers.js").read_text()]
        assert all("how modern AI works, built from scratch" not in t for t in texts)
        assert '">AI Primer</a>' in texts[0] and '">AI Primer</a>' in texts[1]


class TestTheCatalogReadsItsLessons:
    def test_given_a_lesson_whose_file_name_contains_a_part_name_only_the_link_text_is_read(self):
        from tools.docsite import lessons_in_catalog_row

        # "coding_agents.py" contains "agents.py", which isn't a lesson.
        cell = "[agents.llm](../../primer/agents/llm.py), [agents.coding_agents](../../primer/agents/coding_agents.py)"
        assert lessons_in_catalog_row(cell) == ["primer.agents.llm", "primer.agents.coding_agents"]

    def test_given_every_catalog_row_each_lesson_it_names_exists(self):
        from primer.curriculum import CURRICULUM
        from tools.docsite import catalog

        known = {l.module for l in CURRICULUM}
        assert [(p["slug"], m) for p in catalog() for m in p["lessons"] if m not in known] == []


class TestLearningPaths:
    # Paths for different readers, defined once in the curriculum and generated everywhere they appear.

    def test_given_every_learning_path_each_lesson_on_it_exists(self):
        from primer.curriculum import LEARNING_PATHS

        known = {l.module for l in CURRICULUM}
        assert [(p.who, m) for p in LEARNING_PATHS for m in p.route if m not in known] == []

    def test_given_every_learning_path_its_lessons_follow_the_reading_order(self):
        from primer.curriculum import LEARNING_PATHS

        # A path skips lessons but never jumps backwards, so each lesson's prerequisites come first.
        order = {l.module: i for i, l in enumerate(CURRICULUM)}
        assert [p.who for p in LEARNING_PATHS if [order[m] for m in p.route] != sorted(order[m] for m in p.route)] == []

    def test_given_the_home_page_it_offers_every_path_near_the_top(self):
        from primer.curriculum import LEARNING_PATHS
        from tools.docsite import render_home

        home = render_home()
        paths = home.index('id="paths"')
        assert paths < home.index('id="lessons"') and all(p.who in home for p in LEARNING_PATHS)

    def test_given_the_readme_its_learning_paths_are_current(self):
        from primer.curriculum import learning_paths_table

        readme = (ROOT / "README.md").read_text()
        block = readme.split("<!-- BEGIN paths -->\n")[1].split("<!-- END paths -->")[0]
        assert block == learning_paths_table()

    def test_given_the_home_page_and_readme_they_carry_the_subtitle(self):
        from tools.docsite import render_home

        subtitle = "Modern AI from first principles: every concept explained, implemented and tested."
        assert subtitle in render_home() and subtitle in (ROOT / "README.md").read_text()


class TestAPageCanBeSeenAsAPhoneShowsIt:
    # Headless Chrome won't make a window narrower than about 500 pixels, so tools/screenshot.py
    # frames the page at phone width instead, and picks the theme rather than inheriting the machine's.

    def test_given_a_page_it_is_framed_at_phone_width(self):
        from tools.screenshot import frame_page

        assert 'width:390px' in frame_page("papers/hyde.html", theme="light")

    def test_given_a_theme_it_is_chosen_before_the_page_loads(self):
        from tools.screenshot import frame_page

        framed = frame_page("papers/hyde.html", theme="dark")
        assert framed.index('"primer-theme", "dark"') < framed.index("papers/hyde.html")

    def test_given_an_anchor_the_frame_opens_at_it(self):
        from tools.screenshot import frame_page

        assert '"papers/hyde.html#fig1"' in frame_page("papers/hyde.html#fig1", theme="light")

    def test_given_an_anchor_the_frame_scrolls_to_it_after_the_page_has_drawn_itself(self):
        from tools.screenshot import frame_page

        # Math and figures render after load and push the anchor down, so the jump on load lands in the wrong place;
        # and companions scroll smoothly, which never moves in headless Chrome's virtual time, so the scroll is instant.
        framed = frame_page("papers/hyde.html#fig1", theme="light")
        assert "onload" in framed and 'scrollIntoView({ behavior: "instant" })' in framed


class TestLandingABranch:
    # tools/land.py merges a finished branch; generated files are rebuilt, so only real conflicts need a person.

    def test_given_conflicts_only_in_generated_assets_none_need_a_person(self):
        from tools.land import conflicts_needing_a_person

        assert conflicts_needing_a_person(["docs/papers/assets/glossary.js", "docs/papers/assets/catalog.js"]) == []

    def test_given_a_conflict_in_a_lesson_it_needs_a_person(self):
        from tools.land import conflicts_needing_a_person

        assert conflicts_needing_a_person(["docs/papers/assets/glossary.js", "primer/ml/reasoning.py"]) == ["primer/ml/reasoning.py"]


class TestFigureWordsStayReadable:
    # tools/figures.py draws every figure and fails one whose words a line or another panel runs through.

    @staticmethod
    def figure(**kw):
        mpl = pytest.importorskip("matplotlib")
        mpl.use("Agg")
        import matplotlib.pyplot as plt

        return plt.subplots(**kw)

    def test_given_a_line_that_runs_off_the_top_under_the_title_it_is_reported(self):
        from tools.figures import text_collisions

        fig, ax = self.figure()
        ax.set_title("Loss per step")
        ax.plot([0, 1], [0, 10])
        ax.set_ylim(0, 5)  # the line leaves the plot at the top edge, right under the title
        assert any("title" in p for p in text_collisions(fig))

    def test_given_a_line_kept_inside_the_plot_nothing_is_reported(self):
        from tools.figures import text_collisions

        fig, ax = self.figure()
        ax.set_title("Loss per step")
        ax.plot([0, 1], [0, 4])
        ax.set_ylim(0, 5)
        assert text_collisions(fig) == []

    def test_given_a_label_a_line_passes_through_it_is_reported(self):
        from tools.figures import text_collisions

        fig, ax = self.figure()
        ax.plot([0, 1], [0.5, 0.5])
        ax.text(0.5, 0.5, "crossing here", ha="center", va="center")
        assert any("crossing here" in p for p in text_collisions(fig))

    def test_given_panels_so_close_one_panels_labels_sit_on_the_other_it_is_reported(self):
        from tools.figures import text_collisions

        fig, (left, right) = self.figure(ncols=2, figsize=(4, 2))
        fig.subplots_adjust(wspace=0)
        right.set_yticks([0, 1], ["a long tick label", "another long one"])
        assert any("another panel" in p for p in text_collisions(fig))

    def test_given_panels_with_room_between_them_nothing_is_reported(self):
        from tools.figures import text_collisions

        fig, (left, right) = self.figure(ncols=2, figsize=(8, 3), constrained_layout=True)
        right.set_yticks([0, 1], ["a long tick label", "another long one"])
        assert text_collisions(fig) == []

    def test_given_a_guide_line_that_stops_at_the_top_edge_the_title_is_not_reported(self):
        from tools.figures import text_collisions

        # axvline spans the plot exactly; stopping at the edge isn't running into the title.
        fig, ax = self.figure()
        ax.set_title("Same mean, different spread")
        ax.plot([0, 1], [0, 1])
        ax.axvline(0.5, linestyle="--")
        assert text_collisions(fig) == []

    def test_given_a_line_that_ends_at_its_label_it_is_not_reported(self):
        from tools.figures import text_collisions

        # A graph edge ends at the node its letter sits on: it points at the label, it doesn't cross it.
        fig, ax = self.figure()
        ax.plot([0, 1], [0, 1])
        ax.text(1, 1, "H", ha="center", va="center")
        ax.set_xlim(-0.2, 1.2)
        ax.set_ylim(-0.2, 1.2)
        assert text_collisions(fig) == []

    def test_given_a_line_that_runs_off_the_bottom_it_is_reported_as_running_into_the_tick_labels(self):
        from tools.figures import text_collisions

        fig, ax = self.figure()
        ax.plot([0, 1], [1, -5])
        ax.set_ylim(0, 1)
        assert any("bottom" in p for p in text_collisions(fig))

    def test_given_an_arrow_that_ends_on_another_label_it_is_reported(self):
        from tools.figures import text_collisions

        # An arrowhead drawn over a word hides it, whichever label the arrow belongs to.
        fig, ax = self.figure()
        ax.text(0.5, 0.5, "2/4", ha="center", va="center")
        ax.annotate("note", xy=(0.5, 0.5), xytext=(0.9, 0.9), arrowprops=dict(arrowstyle="->"))
        assert any("2/4" in p for p in text_collisions(fig))

    def test_given_a_label_on_an_opaque_background_above_the_line_it_is_not_reported(self):
        from tools.figures import text_collisions

        # The line passes behind the label's box, so the words stay whole.
        fig, ax = self.figure()
        ax.plot([0, 1], [0.5, 0.5], zorder=2)
        ax.text(0.5, 0.5, "crossing here", ha="center", va="center", zorder=3,
                bbox=dict(facecolor="white", edgecolor="none"))
        assert text_collisions(fig) == []

    def test_given_a_tick_outside_the_plots_range_its_undrawn_label_is_not_checked(self):
        from tools.figures import text_collisions

        # Matplotlib keeps labels for ticks beyond the view but never draws them.
        fig, ax = self.figure(layout="constrained")
        im = ax.imshow([[0, 1], [1, 0]])
        ax.set_xticks([-1, 0, 1, 2])
        fig.colorbar(im, ax=ax, fraction=0.3)
        assert text_collisions(fig) == []

    def test_given_an_arrow_leaving_its_own_note_the_note_is_not_reported(self):
        from tools.figures import text_collisions

        # An annotation's own extent includes its arrow; the note is judged by its words alone.
        fig, ax = self.figure()
        ax.annotate("same count,\nnew message", xy=(0.2, 0.2), xytext=(0.6, 0.6), arrowprops=dict(arrowstyle="->"))
        assert text_collisions(fig) == []


# Every lesson has two levels. Level 1 is the practitioner's guide: what the thing is, when
# you need it, how to choose between the options, what it costs, what breaks, who does it
# in the wild. A reader can stop there. Level 2 is the same thing built from scratch (the
# ladder), and on the site its math and code fold into Level 3. Lessons still without a
# guide are declared in primer.curriculum.LEVELS_PENDING, so the set can only shrink.
LEVEL_1 = "## Level 1: The practitioner's guide"
LEVEL_2 = "## Level 2: How it works, from scratch"
GUIDE_LABELS = ["**In one sentence.**", "**When you need it.**", "**Your options.**", "**How to choose.**",
                "**What it costs.**", "**What breaks.**", "**In the wild.**", "**Go deeper.**"]


def lesson_doc(module: str) -> str:
    return importlib.import_module(module).__doc__ or ""


def practitioners_guide(doc: str) -> str:
    return doc.split(LEVEL_1, 1)[1].split(LEVEL_2, 1)[0] if LEVEL_1 in doc else ""


def lessons_with_levels():
    from primer.curriculum import LEVELS_PENDING

    return [l for l in CURRICULUM if l.module not in LEVELS_PENDING]


class TestEveryLessonStartsAtTheTop:
    def test_given_the_curriculum_the_lessons_still_without_a_guide_are_exactly_the_declared_ones(self):
        from primer.curriculum import LEVELS_PENDING

        # A lesson gains its guide and leaves the set in the same change; nothing else touches the set.
        without = {l.module for l in CURRICULUM if LEVEL_1 not in lesson_doc(l.module)}
        assert without == set(LEVELS_PENDING)

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_lesson_its_first_section_is_the_practitioners_guide(self, lesson):
        doc = lesson_doc(lesson.module)
        assert doc.index(LEVEL_1) == doc.index("\n## ") + 1

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_lesson_the_guide_is_followed_by_the_mechanism_built_from_scratch(self, lesson):
        doc = lesson_doc(lesson.module)
        assert LEVEL_2 in doc and doc.index(LEVEL_2) > doc.index(LEVEL_1)
        # Level 2 opens by saying what will be built, before the first mechanism section.
        assert doc.split(LEVEL_2, 1)[1].lstrip().split("\n")[0].strip() != ""

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_guide_it_answers_every_practitioners_question_in_order(self, lesson):
        guide = practitioners_guide(lesson_doc(lesson.module))
        positions = [guide.find(label) for label in GUIDE_LABELS]
        assert [l for l, p in zip(GUIDE_LABELS, positions) if p < 0] == []
        assert positions == sorted(positions)

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_guide_it_lays_the_options_out_as_a_table(self, lesson):
        options = practitioners_guide(lesson_doc(lesson.module)).split("**Your options.**", 1)[1].split("**How to choose.**")[0]
        assert re.search(r"^\|.*\|\n\|[-| :]+\|\n", options, re.M)

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_guide_it_is_a_read_of_a_few_minutes(self, lesson):
        # The level 80% of readers stop at: long enough to decide with, short enough to finish.
        assert 600 <= len(practitioners_guide(lesson_doc(lesson.module)).split()) <= 1600

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_guide_it_holds_no_formula_symbols_table_or_python(self, lesson):
        guide = practitioners_guide(lesson_doc(lesson.module))
        assert [m for m in ("$$", "**Symbols**", "**In Python:**", "```python") if m in guide] == []

    @pytest.mark.parametrize("lesson", lessons_with_levels(), ids=lambda l: getattr(l, "module", ""))
    def test_given_the_guide_it_draws_at_most_one_diagram(self, lesson):
        assert practitioners_guide(lesson_doc(lesson.module)).count("```mermaid") <= 1

    def test_given_every_learning_path_it_says_how_deep_its_reader_goes(self):
        from primer.curriculum import LEARNING_PATHS

        assert all(p.depth in (1, 2, 3) for p in LEARNING_PATHS)
        # The application engineer stops at the guide; the ML engineer reads to the code.
        depth = {p.who: p.depth for p in LEARNING_PATHS}
        assert depth["AI application engineer"] == 1 and depth["ML engineer"] == 3


class TestAReaderDescendsByChoice:
    # tools/docsite.py wraps each level so the page can show one at a time, and folds each formula's
    # decoding into a Level 3 block. A switch in the lesson bar picks the depth; a link into a
    # deeper level opens it.
    PAGE = ('<div class="docstring"><h1 id="t">T</h1><p>intro</p>'
            '<h2 id="level-1-the-practitioners-guide">Level 1: The practitioner\'s guide</h2><p>a</p>'
            '<h2 id="level-2-how-it-works-from-scratch">Level 2: How it works, from scratch</h2><p>b</p>'
            '<h2 id="in-20-seconds">In 20 seconds</h2><p>c</p></div>')

    def test_given_a_lesson_page_each_level_becomes_a_section_the_switch_can_show_or_hide(self):
        from tools.docsite import mark_levels

        out = mark_levels(self.PAGE)
        one, two = out.index('<section class="level level-1" data-level="1">'), out.index('<section class="level level-2" data-level="2">')
        assert one < out.index('<h2 id="level-1') < two < out.index('<h2 id="level-2')
        assert out.count("</section>") == 2 and out.index("<p>c</p>") < out.rindex("</section>") < out.rindex("</div>")

    def test_given_a_page_without_levels_it_is_left_as_it_is(self):
        from tools.docsite import mark_levels

        page = '<div class="docstring"><h2 id="the-idea">The idea</h2><p>x</p></div>'
        assert mark_levels(page) == page

    def test_given_a_formula_it_and_its_symbols_fold_into_a_level_3_block_and_its_reading_stays(self):
        from tools.docsite import fold_math

        # "In words" and "With the numbers" are the Level 2 reading of the formula, so they stay in view.
        html = ('<p>lead</p><p>$$ y = x $$</p><p><strong>Symbols</strong></p><table><tr><td>x</td></tr></table>'
                '<p><strong>In words:</strong> y is x.</p><p><strong>With the numbers:</strong> 2.</p>'
                '<p><strong>In Python:</strong></p><div class="pdoc-code codehilite"><pre>y = x</pre></div><p>after</p>')
        out = fold_math(html)
        assert out.startswith('<p>lead</p><details class="level-3"><summary>Level 3: the formula and its symbols</summary><p>$$')
        assert '</table></details><p><strong>In words:</strong> y is x.</p><p><strong>With the numbers:</strong> 2.</p>' in out
        assert out.endswith('<details class="level-3"><summary>Level 3: in Python</summary><p><strong>In Python:</strong></p>'
                            '<div class="pdoc-code codehilite"><pre>y = x</pre></div></details><p>after</p>')

    def test_given_a_docstring_with_diagrams_and_code_inside_it_level_2_runs_to_its_real_end(self):
        from tools.docsite import mark_levels

        page = ('<div class="docstring"><h2 id="level-1-the-practitioners-guide">L1</h2><p>a</p>'
                '<h2 id="level-2-how-it-works-from-scratch">L2</h2><pre><div class="mermaid">flowchart</div></pre>'
                '<p>Reading it</p><div class="pdoc-code codehilite"><pre>x</pre></div><p>last</p></div><p>outside</p>')
        out = mark_levels(page)
        assert '<p>last</p></section></div><p>outside</p>' in out

    def test_given_the_lesson_bar_it_offers_the_three_levels_as_one_labelled_group(self):
        from tools.docsite import lesson_nav

        bar = lesson_nav("primer.ml.attention", levels=True)
        assert 'role="radiogroup"' in bar and 'aria-label="How deep to read"' in bar
        assert [int(d) for d in re.findall(r'data-depth="(\d)"', bar)] == [1, 2, 3]

    def test_given_a_lesson_still_without_a_guide_its_bar_has_no_switch(self):
        from tools.docsite import lesson_nav

        assert 'role="radiogroup"' not in lesson_nav("primer.ml.attention", levels=False)

    def test_given_a_learning_path_its_links_open_each_lesson_at_the_paths_depth(self):
        from tools.docsite import render_home

        assert 'href="primer/ml/structured_output.html?depth=1"' in render_home()

    def test_given_the_depth_script_it_takes_the_link_first_then_the_readers_last_choice(self):
        from tools.docsite import DEPTH_SCRIPT

        # A path link says ?depth=N; otherwise the reader's previous choice, remembered site-wide.
        assert 'searchParams.get("depth")' in DEPTH_SCRIPT and 'localStorage.getItem("primer-depth")' in DEPTH_SCRIPT
        assert DEPTH_SCRIPT.index('searchParams.get("depth")') < DEPTH_SCRIPT.index('localStorage.getItem("primer-depth")')

    def test_given_a_link_into_a_deeper_level_the_page_descends_to_show_it(self):
        from tools.docsite import DEPTH_SCRIPT

        assert "hashchange" in DEPTH_SCRIPT and "closest" in DEPTH_SCRIPT
